voice = ['af-ZA-AdriNeural',
 'af-ZA-WillemNeural',
 'am-ET-AmehaNeural',
 'am-ET-MekdesNeural',
 'ar-AE-FatimaNeural',
 'ar-AE-HamdanNeural',
 'ar-BH-AliNeural',
 'ar-BH-LailaNeural',
 'ar-DZ-AminaNeural',
 'ar-DZ-IsmaelNeural',
 'ar-EG-SalmaNeural',
 'ar-EG-ShakirNeural',
 'ar-IQ-BasselNeural',
 'ar-IQ-RanaNeural',
 'ar-JO-SanaNeural',
 'ar-JO-TaimNeural',
 'ar-KW-FahedNeural',
 'ar-KW-NouraNeural',
 'ar-LB-LaylaNeural',
 'ar-LB-RamiNeural',
 'ar-LY-ImanNeural',
 'ar-LY-OmarNeural',
 'ar-MA-JamalNeural',
 'ar-MA-MounaNeural',
 'ar-OM-AbdullahNeural',
 'ar-OM-AyshaNeural',
 'ar-QA-AmalNeural',
 'ar-QA-MoazNeural',
 'ar-SA-HamedNeural',
 'ar-SA-ZariyahNeural',
 'ar-SY-AmanyNeural',
 'ar-SY-LaithNeural',
 'ar-TN-HediNeural',
 'ar-TN-ReemNeural',
 'ar-YE-MaryamNeural',
 'ar-YE-SalehNeural',
 'az-AZ-BabekNeural',
 'az-AZ-BanuNeural',
 'bg-BG-BorislavNeural',
 'bg-BG-KalinaNeural',
 'bn-BD-NabanitaNeural',
 'bn-BD-PradeepNeural',
 'bn-IN-BashkarNeural',
 'bn-IN-TanishaaNeural',
 'bs-BA-GoranNeural',
 'bs-BA-VesnaNeural',
 'ca-ES-JoanaNeural',
 'ca-ES-AlbaNeural',
 'ca-ES-EnricNeural',
 'cs-CZ-AntoninNeural',
 'cs-CZ-VlastaNeural',
 'cy-GB-AledNeural',
 'cy-GB-NiaNeural',
 'da-DK-ChristelNeural',
 'da-DK-JeppeNeural',
 'de-AT-IngridNeural',
 'de-AT-JonasNeural',
 'de-CH-JanNeural',
 'de-CH-LeniNeural',
 'de-DE-KatjaNeural',
 'de-DE-AmalaNeural',
 'de-DE-BerndNeural',
 'de-DE-ChristophNeural',
 'de-DE-ConradNeural',
 'de-DE-ElkeNeural',
 'de-DE-GiselaNeural',
 'de-DE-KasperNeural',
 'de-DE-KillianNeural',
 'de-DE-KlarissaNeural',
 'de-DE-KlausNeural',
 'de-DE-LouisaNeural',
 'de-DE-MajaNeural',
 'de-DE-RalfNeural',
 'de-DE-TanjaNeural',
 'el-GR-AthinaNeural',
 'el-GR-NestorasNeural',
 'en-AU-NatashaNeural',
 'en-AU-WilliamNeural',
 'en-CA-ClaraNeural',
 'en-CA-LiamNeural',
 'en-GB-LibbyNeural',
 'en-GB-AbbiNeural',
 'en-GB-AlfieNeural',
 'en-GB-BellaNeural',
 'en-GB-ElliotNeural',
 'en-GB-EthanNeural',
 'en-GB-HollieNeural',
 'en-GB-MaisieNeural',
 'en-GB-NoahNeural',
 'en-GB-OliverNeural',
 'en-GB-OliviaNeural',
 'en-GB-RyanNeural',
 'en-GB-SoniaNeural',
 'en-GB-ThomasNeural',
 'en-GB-MiaNeural',
 'en-HK-SamNeural',
 'en-HK-YanNeural',
 'en-IE-ConnorNeural',
 'en-IE-EmilyNeural',
 'en-IN-NeerjaNeural',
 'en-IN-PrabhatNeural',
 'en-KE-AsiliaNeural',
 'en-KE-ChilembaNeural',
 'en-NG-AbeoNeural',
 'en-NG-EzinneNeural',
 'en-NZ-MitchellNeural',
 'en-NZ-MollyNeural',
 'en-PH-JamesNeural',
 'en-PH-RosaNeural',
 'en-SG-LunaNeural',
 'en-SG-WayneNeural',
 'en-TZ-ElimuNeural',
 'en-TZ-ImaniNeural',
 'en-US-JennyNeural',
 'en-US-JennyMultilingualNeural',
 'en-US-GuyNeural',
 'en-US-AmberNeural',
 'en-US-AnaNeural',
 'en-US-AriaNeural',
 'en-US-AshleyNeural',
 'en-US-BrandonNeural',
 'en-US-ChristopherNeural',
 'en-US-CoraNeural',
 'en-US-ElizabethNeural',
 'en-US-EricNeural',
 'en-US-JacobNeural',
 'en-US-MichelleNeural',
 'en-US-MonicaNeural',
 'en-US-SaraNeural',
 'en-US-AIGenerate1Neural',
 'en-US-AIGenerate2Neural',
 'en-US-DavisNeural',
 'en-US-JaneNeural',
 'en-US-JasonNeural',
 'en-US-NancyNeural',
 'en-US-RogerNeural',
 'en-US-TonyNeural',
 'en-ZA-LeahNeural',
 'en-ZA-LukeNeural',
 'es-AR-ElenaNeural',
 'es-AR-TomasNeural',
 'es-BO-MarceloNeural',
 'es-BO-SofiaNeural',
 'es-CL-CatalinaNeural',
 'es-CL-LorenzoNeural',
 'es-CO-GonzaloNeural',
 'es-CO-SalomeNeural',
 'es-CR-JuanNeural',
 'es-CR-MariaNeural',
 'es-CU-BelkysNeural',
 'es-CU-ManuelNeural',
 'es-DO-EmilioNeural',
 'es-DO-RamonaNeural',
 'es-EC-AndreaNeural',
 'es-EC-LuisNeural',
 'es-ES-AlvaroNeural',
 'es-ES-ElviraNeural',
 'es-GQ-JavierNeural',
 'es-GQ-TeresaNeural',
 'es-GT-AndresNeural',
 'es-GT-MartaNeural',
 'es-HN-CarlosNeural',
 'es-HN-KarlaNeural',
 'es-MX-DaliaNeural',
 'es-MX-JorgeNeural',
 'es-MX-BeatrizNeural',
 'es-MX-CandelaNeural',
 'es-MX-CarlotaNeural',
 'es-MX-CecilioNeural',
 'es-MX-GerardoNeural',
 'es-MX-LarissaNeural',
 'es-MX-LibertoNeural',
 'es-MX-LucianoNeural',
 'es-MX-MarinaNeural',
 'es-MX-NuriaNeural',
 'es-MX-PelayoNeural',
 'es-MX-RenataNeural',
 'es-MX-YagoNeural',
 'es-NI-FedericoNeural',
 'es-NI-YolandaNeural',
 'es-PA-MargaritaNeural',
 'es-PA-RobertoNeural',
 'es-PE-AlexNeural',
 'es-PE-CamilaNeural',
 'es-PR-KarinaNeural',
 'es-PR-VictorNeural',
 'es-PY-MarioNeural',
 'es-PY-TaniaNeural',
 'es-SV-LorenaNeural',
 'es-SV-RodrigoNeural',
 'es-US-AlonsoNeural',
 'es-US-PalomaNeural',
 'es-UY-MateoNeural',
 'es-UY-ValentinaNeural',
 'es-VE-PaolaNeural',
 'es-VE-SebastianNeural',
 'et-EE-AnuNeural',
 'et-EE-KertNeural',
 'fa-IR-DilaraNeural',
 'fa-IR-FaridNeural',
 'fi-FI-SelmaNeural',
 'fi-FI-HarriNeural',
 'fi-FI-NooraNeural',
 'fil-PH-AngeloNeural',
 'fil-PH-BlessicaNeural',
 'fr-BE-CharlineNeural',
 'fr-BE-GerardNeural',
 'fr-CA-SylvieNeural',
 'fr-CA-AntoineNeural',
 'fr-CA-JeanNeural',
 'fr-CH-ArianeNeural',
 'fr-CH-FabriceNeural',
 'fr-FR-AlainNeural',
 'fr-FR-BrigitteNeural',
 'fr-FR-CelesteNeural',
 'fr-FR-ClaudeNeural',
 'fr-FR-CoralieNeural',
 'fr-FR-DeniseNeural',
 'fr-FR-EloiseNeural',
 'fr-FR-HenriNeural',
 'fr-FR-JacquelineNeural',
 'fr-FR-JeromeNeural',
 'fr-FR-JosephineNeural',
 'fr-FR-MauriceNeural',
 'fr-FR-YvesNeural',
 'fr-FR-YvetteNeural',
 'ga-IE-ColmNeural',
 'ga-IE-OrlaNeural',
 'gl-ES-RoiNeural',
 'gl-ES-SabelaNeural',
 'gu-IN-DhwaniNeural',
 'gu-IN-NiranjanNeural',
 'he-IL-AvriNeural',
 'he-IL-HilaNeural',
 'hi-IN-MadhurNeural',
 'hi-IN-SwaraNeural',
 'hr-HR-GabrijelaNeural',
 'hr-HR-SreckoNeural',
 'hu-HU-NoemiNeural',
 'hu-HU-TamasNeural',
 'id-ID-ArdiNeural',
 'id-ID-GadisNeural',
 'is-IS-GudrunNeural',
 'is-IS-GunnarNeural',
 'it-IT-IsabellaNeural',
 'it-IT-DiegoNeural',
 'it-IT-ElsaNeural',
 'it-IT-BenignoNeural',
 'it-IT-CalimeroNeural',
 'it-IT-CataldoNeural',
 'it-IT-FabiolaNeural',
 'it-IT-FiammaNeural',
 'it-IT-GianniNeural',
 'it-IT-ImeldaNeural',
 'it-IT-IrmaNeural',
 'it-IT-LisandroNeural',
 'it-IT-PalmiraNeural',
 'it-IT-PierinaNeural',
 'it-IT-RinaldoNeural',
 'ja-JP-NanamiNeural',
 'ja-JP-KeitaNeural',
 'jv-ID-DimasNeural',
 'jv-ID-SitiNeural',
 'ka-GE-EkaNeural',
 'ka-GE-GiorgiNeural',
 'kk-KZ-AigulNeural',
 'kk-KZ-DauletNeural',
 'km-KH-PisethNeural',
 'km-KH-SreymomNeural',
 'kn-IN-GaganNeural',
 'kn-IN-SapnaNeural',
 'ko-KR-SunHiNeural',
 'ko-KR-InJoonNeural',
 'lo-LA-ChanthavongNeural',
 'lo-LA-KeomanyNeural',
 'lt-LT-LeonasNeural',
 'lt-LT-OnaNeural',
 'lv-LV-EveritaNeural',
 'lv-LV-NilsNeural',
 'mk-MK-AleksandarNeural',
 'mk-MK-MarijaNeural',
 'ml-IN-MidhunNeural',
 'ml-IN-SobhanaNeural',
 'mn-MN-BataaNeural',
 'mn-MN-YesuiNeural',
 'mr-IN-AarohiNeural',
 'mr-IN-ManoharNeural',
 'ms-MY-OsmanNeural',
 'ms-MY-YasminNeural',
 'mt-MT-GraceNeural',
 'mt-MT-JosephNeural',
 'my-MM-NilarNeural',
 'my-MM-ThihaNeural',
 'nb-NO-PernilleNeural',
 'nb-NO-FinnNeural',
 'nb-NO-IselinNeural',
 'ne-NP-HemkalaNeural',
 'ne-NP-SagarNeural',
 'nl-BE-ArnaudNeural',
 'nl-BE-DenaNeural',
 'nl-NL-ColetteNeural',
 'nl-NL-FennaNeural',
 'nl-NL-MaartenNeural',
 'pl-PL-AgnieszkaNeural',
 'pl-PL-MarekNeural',
 'pl-PL-ZofiaNeural',
 'ps-AF-GulNawazNeural',
 'ps-AF-LatifaNeural',
 'pt-BR-FranciscaNeural',
 'pt-BR-AntonioNeural',
 'pt-BR-BrendaNeural',
 'pt-BR-DonatoNeural',
 'pt-BR-ElzaNeural',
 'pt-BR-FabioNeural',
 'pt-BR-GiovannaNeural',
 'pt-BR-HumbertoNeural',
 'pt-BR-JulioNeural',
 'pt-BR-LeilaNeural',
 'pt-BR-LeticiaNeural',
 'pt-BR-ManuelaNeural',
 'pt-BR-NicolauNeural',
 'pt-BR-ValerioNeural',
 'pt-BR-YaraNeural',
 'pt-PT-DuarteNeural',
 'pt-PT-FernandaNeural',
 'pt-PT-RaquelNeural',
 'ro-RO-AlinaNeural',
 'ro-RO-EmilNeural',
 'ru-RU-SvetlanaNeural',
 'ru-RU-DariyaNeural',
 'ru-RU-DmitryNeural',
 'si-LK-SameeraNeural',
 'si-LK-ThiliniNeural',
 'sk-SK-LukasNeural',
 'sk-SK-ViktoriaNeural',
 'sl-SI-PetraNeural',
 'sl-SI-RokNeural',
 'so-SO-MuuseNeural',
 'so-SO-UbaxNeural',
 'sq-AL-AnilaNeural',
 'sq-AL-IlirNeural',
 'sr-RS-NicholasNeural',
 'sr-RS-SophieNeural',
 'su-ID-JajangNeural',
 'su-ID-TutiNeural',
 'sv-SE-SofieNeural',
 'sv-SE-HilleviNeural',
 'sv-SE-MattiasNeural',
 'sw-KE-RafikiNeural',
 'sw-KE-ZuriNeural',
 'sw-TZ-DaudiNeural',
 'sw-TZ-RehemaNeural',
 'ta-IN-PallaviNeural',
 'ta-IN-ValluvarNeural',
 'ta-LK-KumarNeural',
 'ta-LK-SaranyaNeural',
 'ta-MY-KaniNeural',
 'ta-MY-SuryaNeural',
 'ta-SG-AnbuNeural',
 'ta-SG-VenbaNeural',
 'te-IN-MohanNeural',
 'te-IN-ShrutiNeural',
 'th-TH-PremwadeeNeural',
 'th-TH-AcharaNeural',
 'th-TH-NiwatNeural',
 'tr-TR-AhmetNeural',
 'tr-TR-EmelNeural',
 'uk-UA-OstapNeural',
 'uk-UA-PolinaNeural',
 'ur-IN-GulNeural',
 'ur-IN-SalmanNeural',
 'ur-PK-AsadNeural',
 'ur-PK-UzmaNeural',
 'uz-UZ-MadinaNeural',
 'uz-UZ-SardorNeural',
 'vi-VN-HoaiMyNeural',
 'vi-VN-NamMinhNeural',
 'zh-CN-XiaoxiaoNeural',
 'zh-CN-YunyangNeural',
 'zh-CN-XiaochenNeural',
 'zh-CN-XiaohanNeural',
 'zh-CN-XiaomoNeural',
 'zh-CN-XiaoqiuNeural',
 'zh-CN-XiaoruiNeural',
 'zh-CN-XiaoshuangNeural',
 'zh-CN-XiaoxuanNeural',
 'zh-CN-XiaoyanNeural',
 'zh-CN-XiaoyouNeural',
 'zh-CN-YunxiNeural',
 'zh-CN-YunyeNeural',
 'zh-CN-XiaomengNeural',
 'zh-CN-XiaoyiNeural',
 'zh-CN-XiaozhenNeural',
 'zh-CN-YunfengNeural',
 'zh-CN-YunhaoNeural',
 'zh-CN-YunjianNeural',
 'zh-CN-YunxiaNeural',
 'zh-CN-YunzeNeural',
 'zh-CN-henan-YundengNeural',
 'zh-CN-liaoning-XiaobeiNeural',
 'zh-CN-shaanxi-XiaoniNeural',
 'zh-CN-shandong-YunxiangNeural',
 'zh-CN-sichuan-YunxiNeural',
 'zh-HK-HiuMaanNeural',
 'zh-HK-HiuGaaiNeural',
 'zh-HK-WanLungNeural',
 'zh-TW-HsiaoChenNeural',
 'zh-TW-HsiaoYuNeural',
 'zh-TW-YunJheNeural',
 'zu-ZA-ThandoNeural',
 'zu-ZA-ThembaNeural']













tts_voice = ['af-ZA-AdriNeural',
 'af-ZA-WillemNeural',
 'am-ET-AmehaNeural',
 'am-ET-MekdesNeural',
 'ar-AE-FatimaNeural',
 'ar-AE-HamdanNeural',
 'ar-BH-AliNeural',
 'ar-BH-LailaNeural',
 'ar-DZ-IsmaelNeural',
 'ar-EG-SalmaNeural',
 'ar-EG-ShakirNeural',
 'ar-IQ-BasselNeural',
 'ar-IQ-RanaNeural',
 'ar-JO-SanaNeural',
 'ar-JO-TaimNeural',
 'ar-KW-FahedNeural',
 'ar-KW-NouraNeural',
 'ar-LB-LaylaNeural',
 'ar-LB-RamiNeural',
 'ar-LY-ImanNeural',
 'ar-LY-OmarNeural',
 'ar-MA-JamalNeural',
 'ar-MA-MounaNeural',
 'ar-OM-AbdullahNeural',
 'ar-OM-AyshaNeural',
 'ar-QA-AmalNeural',
 'ar-QA-MoazNeural',
 'ar-SA-HamedNeural',
 'ar-SA-ZariyahNeural',
 'ar-SY-AmanyNeural',
 'ar-SY-LaithNeural',
 'ar-TN-HediNeural',
 'ar-TN-ReemNeural',
 'ar-YE-MaryamNeural',
 'ar-YE-SalehNeural',
 'az-AZ-BabekNeural',
 'az-AZ-BanuNeural',
 'bg-BG-BorislavNeural',
 'bg-BG-KalinaNeural',
 'bn-BD-NabanitaNeural',
 'bn-BD-PradeepNeural',
 'bn-IN-BashkarNeural',
 'bn-IN-TanishaaNeural',
 'bs-BA-GoranNeural',
 'bs-BA-VesnaNeural',
 'ca-ES-JoanaNeural',
 'ca-ES-EnricNeural',
 'cs-CZ-AntoninNeural',
 'cs-CZ-VlastaNeural',
 'cy-GB-AledNeural',
 'cy-GB-NiaNeural',
 'da-DK-ChristelNeural',
 'da-DK-JeppeNeural',
 'de-AT-IngridNeural',
 'de-AT-JonasNeural',
 'de-CH-JanNeural',
 'de-CH-LeniNeural',
 'de-DE-KatjaNeural',
 'de-DE-AmalaNeural',
 'de-DE-ConradNeural',
 'de-DE-KillianNeural',
 'el-GR-AthinaNeural',
 'el-GR-NestorasNeural',
 'en-AU-NatashaNeural',
 'en-AU-WilliamNeural',
 'en-CA-ClaraNeural',
 'en-CA-LiamNeural',
 'en-GB-LibbyNeural',
 'en-GB-MaisieNeural',
 'en-GB-RyanNeural',
 'en-GB-SoniaNeural',
 'en-GB-ThomasNeural',
 'en-HK-SamNeural',
 'en-HK-YanNeural',
 'en-IE-ConnorNeural',
 'en-IE-EmilyNeural',
 'en-IN-NeerjaNeural',
 'en-IN-PrabhatNeural',
 'en-KE-AsiliaNeural',
 'en-KE-ChilembaNeural',
 'en-NG-AbeoNeural',
 'en-NG-EzinneNeural',
 'en-NZ-MitchellNeural',
 'en-PH-JamesNeural',
 'en-PH-RosaNeural',
 'en-SG-LunaNeural',
 'en-SG-WayneNeural',
 'en-TZ-ElimuNeural',
 'en-TZ-ImaniNeural',
 'en-US-JennyNeural',
 'en-US-GuyNeural',
 'en-US-AnaNeural',
 'en-US-AriaNeural',
 'en-US-ChristopherNeural',
 'en-US-EricNeural',
 'en-US-MichelleNeural',
 'en-US-RogerNeural',
 'en-ZA-LeahNeural',
 'en-ZA-LukeNeural',
 'es-AR-ElenaNeural',
 'es-AR-TomasNeural',
 'es-BO-MarceloNeural',
 'es-BO-SofiaNeural',
 'es-CO-GonzaloNeural',
 'es-CO-SalomeNeural',
 'es-CR-JuanNeural',
 'es-CR-MariaNeural',
 'es-CU-BelkysNeural',
 'es-DO-EmilioNeural',
 'es-DO-RamonaNeural',
 'es-EC-AndreaNeural',
 'es-EC-LuisNeural',
 'es-ES-AlvaroNeural',
 'es-ES-ElviraNeural',
 'es-GQ-TeresaNeural',
 'es-GT-AndresNeural',
 'es-GT-MartaNeural',
 'es-HN-CarlosNeural',
 'es-HN-KarlaNeural',
 'es-MX-DaliaNeural',
 'es-MX-JorgeNeural',
 'es-NI-FedericoNeural',
 'es-NI-YolandaNeural',
 'es-PA-MargaritaNeural',
 'es-PA-RobertoNeural',
 'es-PE-AlexNeural',
 'es-PE-CamilaNeural',
 'es-PR-KarinaNeural',
 'es-PR-VictorNeural',
 'es-PY-MarioNeural',
 'es-PY-TaniaNeural',
 'es-SV-LorenaNeural',
 'es-SV-RodrigoNeural',
 'es-US-AlonsoNeural',
 'es-US-PalomaNeural',
 'es-UY-MateoNeural',
 'es-UY-ValentinaNeural',
 'es-VE-PaolaNeural',
 'es-VE-SebastianNeural',
 'et-EE-AnuNeural',
 'et-EE-KertNeural',
 'fa-IR-DilaraNeural',
 'fa-IR-FaridNeural',
 'fi-FI-HarriNeural',
 'fi-FI-NooraNeural',
 'fr-BE-CharlineNeural',
 'fr-BE-GerardNeural',
 'fr-CA-SylvieNeural',
 'fr-CA-AntoineNeural',
 'fr-CA-JeanNeural',
 'fr-CH-ArianeNeural',
 'fr-CH-FabriceNeural',
 'fr-FR-DeniseNeural',
 'fr-FR-EloiseNeural',
 'fr-FR-HenriNeural',
 'ga-IE-ColmNeural',
 'ga-IE-OrlaNeural',
 'gl-ES-RoiNeural',
 'gl-ES-SabelaNeural',
 'gu-IN-DhwaniNeural',
 'gu-IN-NiranjanNeural',
 'he-IL-AvriNeural',
 'he-IL-HilaNeural',
 'hi-IN-MadhurNeural',
 'hi-IN-SwaraNeural',
 'hr-HR-GabrijelaNeural',
 'hr-HR-SreckoNeural',
 'hu-HU-NoemiNeural',
 'hu-HU-TamasNeural',
 'id-ID-ArdiNeural',
 'id-ID-GadisNeural',
 'is-IS-GudrunNeural',
 'is-IS-GunnarNeural',
 'it-IT-IsabellaNeural',
 'it-IT-DiegoNeural',
 'it-IT-ElsaNeural',
 'ja-JP-NanamiNeural',
 'ja-JP-KeitaNeural',
 'jv-ID-DimasNeural',
 'jv-ID-SitiNeural',
 'ka-GE-EkaNeural',
 'ka-GE-GiorgiNeural',
 'kk-KZ-AigulNeural',
 'kk-KZ-DauletNeural',
 'km-KH-PisethNeural',
 'km-KH-SreymomNeural',
 'kn-IN-GaganNeural',
 'kn-IN-SapnaNeural',
 'ko-KR-SunHiNeural',
 'ko-KR-InJoonNeural',
 'lo-LA-ChanthavongNeural',
 'lo-LA-KeomanyNeural',
 'lt-LT-LeonasNeural',
 'lt-LT-OnaNeural',
 'lv-LV-EveritaNeural',
 'lv-LV-NilsNeural',
 'mk-MK-AleksandarNeural',
 'mk-MK-MarijaNeural',
 'ml-IN-MidhunNeural',
 'ml-IN-SobhanaNeural',
 'mn-MN-BataaNeural',
 'mn-MN-YesuiNeural',
 'mr-IN-AarohiNeural',
 'mr-IN-ManoharNeural',
 'ms-MY-OsmanNeural',
 'ms-MY-YasminNeural',
 'mt-MT-GraceNeural',
 'mt-MT-JosephNeural',
 'my-MM-NilarNeural',
 'my-MM-ThihaNeural',
 'nb-NO-PernilleNeural',
 'nb-NO-FinnNeural',
 'ne-NP-HemkalaNeural',
 'ne-NP-SagarNeural',
 'nl-BE-ArnaudNeural',
 'nl-BE-DenaNeural',
 'nl-NL-ColetteNeural',
 'nl-NL-FennaNeural',
 'nl-NL-MaartenNeural',
 'pl-PL-MarekNeural',
 'pl-PL-ZofiaNeural',
 'ps-AF-GulNawazNeural',
 'ps-AF-LatifaNeural',
 'pt-BR-FranciscaNeural',
 'pt-BR-AntonioNeural',
 'pt-PT-DuarteNeural',
 'pt-PT-RaquelNeural',
 'ro-RO-AlinaNeural',
 'ro-RO-EmilNeural',
 'ru-RU-SvetlanaNeural',
 'ru-RU-DmitryNeural',
 'si-LK-SameeraNeural',
 'si-LK-ThiliniNeural',
 'sk-SK-LukasNeural',
 'sk-SK-ViktoriaNeural',
 'sl-SI-PetraNeural',
 'sl-SI-RokNeural',
 'so-SO-MuuseNeural',
 'so-SO-UbaxNeural',
 'sq-AL-AnilaNeural',
 'sq-AL-IlirNeural',
 'sr-RS-NicholasNeural',
 'sr-RS-SophieNeural',
 'su-ID-JajangNeural',
 'su-ID-TutiNeural',
 'sv-SE-SofieNeural',
 'sv-SE-MattiasNeural',
 'sw-KE-RafikiNeural',
 'sw-KE-ZuriNeural',
 'sw-TZ-DaudiNeural',
 'sw-TZ-RehemaNeural',
 'ta-IN-PallaviNeural',
 'ta-IN-ValluvarNeural',
 'ta-LK-KumarNeural',
 'ta-LK-SaranyaNeural',
 'ta-MY-KaniNeural',
 'ta-MY-SuryaNeural',
 'ta-SG-AnbuNeural',
 'te-IN-MohanNeural',
 'te-IN-ShrutiNeural',
 'th-TH-PremwadeeNeural',
 'th-TH-NiwatNeural',
 'tr-TR-AhmetNeural',
 'tr-TR-EmelNeural',
 'uk-UA-OstapNeural',
 'uk-UA-PolinaNeural',
 'ur-IN-GulNeural',
 'ur-IN-SalmanNeural',
 'ur-PK-AsadNeural',
 'ur-PK-UzmaNeural',
 'uz-UZ-MadinaNeural',
 'uz-UZ-SardorNeural',
 'vi-VN-HoaiMyNeural',
 'vi-VN-NamMinhNeural',
 'zh-CN-XiaoxiaoNeural',
 'zh-CN-YunyangNeural',
 'zh-CN-YunxiNeural',
 'zh-CN-XiaoyiNeural',
 'zh-CN-YunjianNeural',
 'zh-CN-YunxiaNeural',
 'zh-CN-liaoning-XiaobeiNeural',
 'zh-CN-shaanxi-XiaoniNeural',
 'zh-HK-HiuMaanNeural',
 'zh-HK-HiuGaaiNeural',
 'zh-HK-WanLungNeural',
 'zh-TW-HsiaoChenNeural',
 'zh-TW-HsiaoYuNeural',
 'zh-TW-YunJheNeural',
 'zu-ZA-ThandoNeural',
 'zu-ZA-ThembaNeural']





tts_dict = {'Afrikaans (South Africa)-Adri-Female': 'af-ZA-AdriNeural',
 'Afrikaans (South Africa)-Willem-Male': 'af-ZA-WillemNeural',
 'Amharic (Ethiopia)-Ameha-Male': 'am-ET-AmehaNeural',
 'Amharic (Ethiopia)-Mekdes-Female': 'am-ET-MekdesNeural',
 'Arabic (United Arab Emirates)-Fatima-Female': 'ar-AE-FatimaNeural',
 'Arabic (United Arab Emirates)-Hamdan-Male': 'ar-AE-HamdanNeural',
 'Arabic (Bahrain)-Ali-Male': 'ar-BH-AliNeural',
 'Arabic (Bahrain)-Laila-Female': 'ar-BH-LailaNeural',
 'Arabic (Algeria)-Ismael-Male': 'ar-DZ-IsmaelNeural',
 'Arabic (Egypt)-Salma-Female': 'ar-EG-SalmaNeural',
 'Arabic (Egypt)-Shakir-Male': 'ar-EG-ShakirNeural',
 'Arabic (Iraq)-Bassel-Male': 'ar-IQ-BasselNeural',
 'Arabic (Iraq)-Rana-Female': 'ar-IQ-RanaNeural',
 'Arabic (Jordan)-Sana-Female': 'ar-JO-SanaNeural',
 'Arabic (Jordan)-Taim-Male': 'ar-JO-TaimNeural',
 'Arabic (Kuwait)-Fahed-Male': 'ar-KW-FahedNeural',
 'Arabic (Kuwait)-Noura-Female': 'ar-KW-NouraNeural',
 'Arabic (Lebanon)-Layla-Female': 'ar-LB-LaylaNeural',
 'Arabic (Lebanon)-Rami-Male': 'ar-LB-RamiNeural',
 'Arabic (Libya)-Iman-Female': 'ar-LY-ImanNeural',
 'Arabic (Libya)-Omar-Male': 'ar-LY-OmarNeural',
 'Arabic (Morocco)-Jamal-Male': 'ar-MA-JamalNeural',
 'Arabic (Morocco)-Mouna-Female': 'ar-MA-MounaNeural',
 'Arabic (Oman)\u200b-Abdullah-Male': 'ar-OM-AbdullahNeural',
 'Arabic (Oman)\u200b-Aysha-Female': 'ar-OM-AyshaNeural',
 'Arabic (Qatar)-Amal-Female': 'ar-QA-AmalNeural',
 'Arabic (Qatar)-Moaz-Male': 'ar-QA-MoazNeural',
 'Arabic (Saudi Arabia)-Hamed-Male': 'ar-SA-HamedNeural',
 'Arabic (Saudi Arabia)-Zariyah-Female': 'ar-SA-ZariyahNeural',
 'Arabic (Syria)-Amany-Female': 'ar-SY-AmanyNeural',
 'Arabic (Syria)-Laith-Male': 'ar-SY-LaithNeural',
 'Arabic (Tunisia)-Hedi-Male': 'ar-TN-HediNeural',
 'Arabic (Tunisia)-Reem-Female': 'ar-TN-ReemNeural',
 'Arabic (Yemen)-Maryam-Female': 'ar-YE-MaryamNeural',
 'Arabic (Yemen)-Saleh-Male': 'ar-YE-SalehNeural',
 'Azerbaijani (Azerbaijan)-Babek-Male': 'az-AZ-BabekNeural',
 'Azerbaijani (Azerbaijan)-Banu-Female': 'az-AZ-BanuNeural',
 'Bulgarian (Bulgaria)-Borislav-Male': 'bg-BG-BorislavNeural',
 'Bulgarian (Bulgaria)-Kalina-Female': 'bg-BG-KalinaNeural',
 'Bangla (Bangladesh)-Nabanita-Female': 'bn-BD-NabanitaNeural',
 'Bangla (Bangladesh)-Pradeep-Male': 'bn-BD-PradeepNeural',
 'Bengali (India)-Bashkar-Male': 'bn-IN-BashkarNeural',
 'Bengali (India)-Tanishaa-Female': 'bn-IN-TanishaaNeural',
 'Bosnian (Bosnia)-Goran-Male': 'bs-BA-GoranNeural',
 'Bosnian (Bosnia)-Vesna-Female': 'bs-BA-VesnaNeural',
 'Catalan (Spain)-Joana-Female': 'ca-ES-JoanaNeural',
 'Catalan (Spain)-Enric-Male': 'ca-ES-EnricNeural',
 'Czech (Czech)-Antonin-Male': 'cs-CZ-AntoninNeural',
 'Czech (Czech)-Vlasta-Female': 'cs-CZ-VlastaNeural',
 'Welsh (United Kingdom)-Aled-Male': 'cy-GB-AledNeural',
 'Welsh (United Kingdom)-Nia-Female': 'cy-GB-NiaNeural',
 'Danish (Denmark)-Christel-Female': 'da-DK-ChristelNeural',
 'Danish (Denmark)-Jeppe-Male': 'da-DK-JeppeNeural',
 'German (Austria)-Ingrid-Female': 'de-AT-IngridNeural',
 'German (Austria)-Jonas-Male': 'de-AT-JonasNeural',
 'German (Switzerland)-Jan-Male': 'de-CH-JanNeural',
 'German (Switzerland)-Leni-Female': 'de-CH-LeniNeural',
 'German (Germany)-Katja-Female': 'de-DE-KatjaNeural',
 'German (Germany)-Amala-Female': 'de-DE-AmalaNeural',
 'German (Germany)-Conrad-Male': 'de-DE-ConradNeural',
 'German (Germany)-Killian-Male': 'de-DE-KillianNeural',
 'Greek (Greece)-Athina-Female': 'el-GR-AthinaNeural',
 'Greek (Greece)-Nestoras-Male': 'el-GR-NestorasNeural',
 'English (Australia)-Natasha-Female': 'en-AU-NatashaNeural',
 'English (Australia)-William-Male': 'en-AU-WilliamNeural',
 'English (Canada)-Clara-Female': 'en-CA-ClaraNeural',
 'English (Canada)-Liam-Male': 'en-CA-LiamNeural',
 'English (United Kingdom)-Libby-Female': 'en-GB-LibbyNeural',
 'English (United Kingdom)-Maisie-Female': 'en-GB-MaisieNeural',
 'English (United Kingdom)-Ryan-Male': 'en-GB-RyanNeural',
 'English (United Kingdom)-Sonia-Female': 'en-GB-SoniaNeural',
 'English (United Kingdom)-Thomas-Male': 'en-GB-ThomasNeural',
 'English (Hongkong)-Sam-Male': 'en-HK-SamNeural',
 'English (Hongkong)-Yan-Female': 'en-HK-YanNeural',
 'English (Ireland)-Connor-Male': 'en-IE-ConnorNeural',
 'English (Ireland)-Emily-Female': 'en-IE-EmilyNeural',
 'English (India)-Neerja-Female': 'en-IN-NeerjaNeural',
 'English (India)-Prabhat-Male': 'en-IN-PrabhatNeural',
 'English (Kenya)-Asilia-Female': 'en-KE-AsiliaNeural',
 'English (Kenya)-Chilemba-Male': 'en-KE-ChilembaNeural',
 'English (Nigeria)-Abeo-Male': 'en-NG-AbeoNeural',
 'English (Nigeria)-Ezinne-Female': 'en-NG-EzinneNeural',
 'English (New Zealand)-Mitchell-Male': 'en-NZ-MitchellNeural',
 'English (Philippines)-James-Male': 'en-PH-JamesNeural',
 'English (Philippines)-Rosa-Female': 'en-PH-RosaNeural',
 'English (Singapore)-Luna-Female': 'en-SG-LunaNeural',
 'English (Singapore)-Wayne-Male': 'en-SG-WayneNeural',
 'English (Tanzania)-Elimu-Male': 'en-TZ-ElimuNeural',
 'English (Tanzania)-Imani-Female': 'en-TZ-ImaniNeural',
 'English (United States)-Jenny-Female': 'en-US-JennyNeural',
 'English (United States)-Guy-Male': 'en-US-GuyNeural',
 'English (United States)-Ana-Female': 'en-US-AnaNeural',
 'English (United States)-Aria-Female': 'en-US-AriaNeural',
 'English (United States)-Christopher-Male': 'en-US-ChristopherNeural',
 'English (United States)-Eric-Male': 'en-US-EricNeural',
 'English (United States)-Michelle-Female': 'en-US-MichelleNeural',
 'English (United States)-Roger-Male': 'en-US-RogerNeural',
 'English (South Africa)-Leah-Female': 'en-ZA-LeahNeural',
 'English (South Africa)-Luke-Male': 'en-ZA-LukeNeural',
 'Spanish (Argentina)-Elena-Female': 'es-AR-ElenaNeural',
 'Spanish (Argentina)-Tomas-Male': 'es-AR-TomasNeural',
 'Spanish (Bolivia)-Marcelo-Male': 'es-BO-MarceloNeural',
 'Spanish (Bolivia)-Sofia-Female': 'es-BO-SofiaNeural',
 'Spanish (Colombia)-Gonzalo-Male': 'es-CO-GonzaloNeural',
 'Spanish (Colombia)-Salome-Female': 'es-CO-SalomeNeural',
 'Spanish (Costa Rica)-Juan-Male': 'es-CR-JuanNeural',
 'Spanish (Costa Rica)-Maria-Female': 'es-CR-MariaNeural',
 'Spanish (Cuba)-Belkys-Female': 'es-CU-BelkysNeural',
 'Spanish (Dominican Republic)-Emilio-Male': 'es-DO-EmilioNeural',
 'Spanish (Dominican Republic)-Ramona-Female': 'es-DO-RamonaNeural',
 'Spanish (Ecuador)-Andrea-Female': 'es-EC-AndreaNeural',
 'Spanish (Ecuador)-Luis-Male': 'es-EC-LuisNeural',
 'Spanish (Spain)-Alvaro-Male': 'es-ES-AlvaroNeural',
 'Spanish (Spain)-Elvira-Female': 'es-ES-ElviraNeural',
 'Spanish (Equatorial Guinea)-Teresa-Female': 'es-GQ-TeresaNeural',
 'Spanish (Guatemala)-Andres-Male': 'es-GT-AndresNeural',
 'Spanish (Guatemala)-Marta-Female': 'es-GT-MartaNeural',
 'Spanish (Honduras)-Carlos-Male': 'es-HN-CarlosNeural',
 'Spanish (Honduras)-Karla-Female': 'es-HN-KarlaNeural',
 'Spanish (Mexico)-Dalia-Female': 'es-MX-DaliaNeural',
 'Spanish (Mexico)-Jorge-Male': 'es-MX-JorgeNeural',
 'Spanish (Nicaragua)-Federico-Male': 'es-NI-FedericoNeural',
 'Spanish (Nicaragua)-Yolanda-Female': 'es-NI-YolandaNeural',
 'Spanish (Panama)-Margarita-Female': 'es-PA-MargaritaNeural',
 'Spanish (Panama)-Roberto-Male': 'es-PA-RobertoNeural',
 'Spanish (Peru)-Alex-Male': 'es-PE-AlexNeural',
 'Spanish (Peru)-Camila-Female': 'es-PE-CamilaNeural',
 'Spanish (Puerto Rico)-Karina-Female': 'es-PR-KarinaNeural',
 'Spanish (Puerto Rico)-Victor-Male': 'es-PR-VictorNeural',
 'Spanish (Paraguay)-Mario-Male': 'es-PY-MarioNeural',
 'Spanish (Paraguay)-Tania-Female': 'es-PY-TaniaNeural',
 'Spanish (El Salvador)-Lorena-Female': 'es-SV-LorenaNeural',
 'Spanish (El Salvador)-Rodrigo-Male': 'es-SV-RodrigoNeural',
 'Spanish (United States)-Alonso-Male': 'es-US-AlonsoNeural',
 'Spanish (United States)-Paloma-Female': 'es-US-PalomaNeural',
 'Spanish (Uruguay)-Mateo-Male': 'es-UY-MateoNeural',
 'Spanish (Uruguay)-Valentina-Female': 'es-UY-ValentinaNeural',
 'Spanish (Venezuela)-Paola-Female': 'es-VE-PaolaNeural',
 'Spanish (Venezuela)-Sebastian-Male': 'es-VE-SebastianNeural',
 'Estonian (Estonia)-Anu-Female': 'et-EE-AnuNeural',
 'Estonian (Estonia)-Kert-Male': 'et-EE-KertNeural',
 'Persian (Iran)-Dilara-Female': 'fa-IR-DilaraNeural',
 'Persian (Iran)-Farid-Male': 'fa-IR-FaridNeural',
 'Finnish (Finland)-Harri-Male': 'fi-FI-HarriNeural',
 'Finnish (Finland)-Noora-Female': 'fi-FI-NooraNeural',
 'French (Belgium)-Charline-Female': 'fr-BE-CharlineNeural',
 'French (Belgium)-Gerard-Male': 'fr-BE-GerardNeural',
 'French (Canada)-Sylvie-Female': 'fr-CA-SylvieNeural',
 'French (Canada)-Antoine-Male': 'fr-CA-AntoineNeural',
 'French (Canada)-Jean-Male': 'fr-CA-JeanNeural',
 'French (Switzerland)-Ariane-Female': 'fr-CH-ArianeNeural',
 'French (Switzerland)-Fabrice-Male': 'fr-CH-FabriceNeural',
 'French (France)-Denise-Female': 'fr-FR-DeniseNeural',
 'French (France)-Eloise-Female': 'fr-FR-EloiseNeural',
 'French (France)-Henri-Male': 'fr-FR-HenriNeural',
 'Irish (Ireland)-Colm-Male': 'ga-IE-ColmNeural',
 'Irish (Ireland)-Orla-Female': 'ga-IE-OrlaNeural',
 'Galician (Spain)-Roi-Male': 'gl-ES-RoiNeural',
 'Galician (Spain)-Sabela-Female': 'gl-ES-SabelaNeural',
 'Gujarati (India)-Dhwani-Female': 'gu-IN-DhwaniNeural',
 'Gujarati (India)-Niranjan-Male': 'gu-IN-NiranjanNeural',
 'Hebrew (Israel)-Avri-Male': 'he-IL-AvriNeural',
 'Hebrew (Israel)-Hila-Female': 'he-IL-HilaNeural',
 'Hindi (India)-Madhur-Male': 'hi-IN-MadhurNeural',
 'Hindi (India)-Swara-Female': 'hi-IN-SwaraNeural',
 'Croatian (Croatia)-Gabrijela-Female': 'hr-HR-GabrijelaNeural',
 'Croatian (Croatia)-Srecko-Male': 'hr-HR-SreckoNeural',
 'Hungarian (Hungary)-Noemi-Female': 'hu-HU-NoemiNeural',
 'Hungarian (Hungary)-Tamas-Male': 'hu-HU-TamasNeural',
 'Indonesian (Indonesia)-Ardi-Male': 'id-ID-ArdiNeural',
 'Indonesian (Indonesia)-Gadis-Female': 'id-ID-GadisNeural',
 'Icelandic (Iceland)-Gudrun-Female': 'is-IS-GudrunNeural',
 'Icelandic (Iceland)-Gunnar-Male': 'is-IS-GunnarNeural',
 'Italian (Italy)-Isabella-Female': 'it-IT-IsabellaNeural',
 'Italian (Italy)-Diego-Male': 'it-IT-DiegoNeural',
 'Italian (Italy)-Elsa-Female': 'it-IT-ElsaNeural',
 'Japanese (Japan)-Nanami-Female': 'ja-JP-NanamiNeural',
 'Japanese (Japan)-Keita-Male': 'ja-JP-KeitaNeural',
 'Javanese (Indonesia)-Dimas-Male': 'jv-ID-DimasNeural',
 'Javanese (Indonesia)-Siti-Female': 'jv-ID-SitiNeural',
 'Georgian (Georgia)-Eka-Female': 'ka-GE-EkaNeural',
 'Georgian (Georgia)-Giorgi-Male': 'ka-GE-GiorgiNeural',
 'Kazakh (Kazakhstan)-Aigul-Female': 'kk-KZ-AigulNeural',
 'Kazakh (Kazakhstan)-Daulet-Male': 'kk-KZ-DauletNeural',
 'Khmer (Cambodia)-Piseth-Male': 'km-KH-PisethNeural',
 'Khmer (Cambodia)-Sreymom-Female': 'km-KH-SreymomNeural',
 'Kannada (India)-Gagan-Male': 'kn-IN-GaganNeural',
 'Kannada (India)-Sapna-Female': 'kn-IN-SapnaNeural',
 'Korean (Korea)-Sun-Hi-Female': 'ko-KR-SunHiNeural',
 'Korean (Korea)-InJoon-Male': 'ko-KR-InJoonNeural',
 'Lao (Laos)-Chanthavong-Male': 'lo-LA-ChanthavongNeural',
 'Lao (Laos)-Keomany-Female': 'lo-LA-KeomanyNeural',
 'Lithuanian (Lithuania)-Leonas-Male': 'lt-LT-LeonasNeural',
 'Lithuanian (Lithuania)-Ona-Female': 'lt-LT-OnaNeural',
 'Latvian (Latvia)-Everita-Female': 'lv-LV-EveritaNeural',
 'Latvian (Latvia)-Nils-Male': 'lv-LV-NilsNeural',
 'Macedonian (Republic of North Macedonia)-Aleksandar-Male': 'mk-MK-AleksandarNeural',
 'Macedonian (Republic of North Macedonia)-Marija-Female': 'mk-MK-MarijaNeural',
 'Malayalam (India)-Midhun-Male': 'ml-IN-MidhunNeural',
 'Malayalam (India)-Sobhana-Female': 'ml-IN-SobhanaNeural',
 'Mongolian (Mongolia)-Bataa-Male': 'mn-MN-BataaNeural',
 'Mongolian (Mongolia)-Yesui-Female': 'mn-MN-YesuiNeural',
 'Marathi (India)-Aarohi-Female': 'mr-IN-AarohiNeural',
 'Marathi (India)-Manohar-Male': 'mr-IN-ManoharNeural',
 'Malay (Malaysia)-Osman-Male': 'ms-MY-OsmanNeural',
 'Malay (Malaysia)-Yasmin-Female': 'ms-MY-YasminNeural',
 'Maltese (Malta)-Grace-Female': 'mt-MT-GraceNeural',
 'Maltese (Malta)-Joseph-Male': 'mt-MT-JosephNeural',
 'Burmese (Myanmar)-Nilar-Female': 'my-MM-NilarNeural',
 'Burmese (Myanmar)-Thiha-Male': 'my-MM-ThihaNeural',
 'Norwegian (Bokmål, Norway)-Pernille-Female': 'nb-NO-PernilleNeural',
 'Norwegian (Bokmål, Norway)-Finn-Male': 'nb-NO-FinnNeural',
 'Nepali (Nepal)-Hemkala-Female': 'ne-NP-HemkalaNeural',
 'Nepali (Nepal)-Sagar-Male': 'ne-NP-SagarNeural',
 'Dutch (Belgium)-Arnaud-Male': 'nl-BE-ArnaudNeural',
 'Dutch (Belgium)-Dena-Female': 'nl-BE-DenaNeural',
 'Dutch (Netherlands)-Colette-Female': 'nl-NL-ColetteNeural',
 'Dutch (Netherlands)-Fenna-Female': 'nl-NL-FennaNeural',
 'Dutch (Netherlands)-Maarten-Male': 'nl-NL-MaartenNeural',
 'Polish (Poland)-Marek-Male': 'pl-PL-MarekNeural',
 'Polish (Poland)-Zofia-Female': 'pl-PL-ZofiaNeural',
 'Pashto (Afghanistan)-Gul Nawaz-Male': 'ps-AF-GulNawazNeural',
 'Pashto (Afghanistan)-Latifa-Female': 'ps-AF-LatifaNeural',
 'Portuguese (Brazil)-Francisca-Female': 'pt-BR-FranciscaNeural',
 'Portuguese (Brazil)-Antonio-Male': 'pt-BR-AntonioNeural',
 'Portuguese (Portugal)-Duarte-Male': 'pt-PT-DuarteNeural',
 'Portuguese (Portugal)-Raquel-Female': 'pt-PT-RaquelNeural',
 'Romanian (Romania)-Alina-Female': 'ro-RO-AlinaNeural',
 'Romanian (Romania)-Emil-Male': 'ro-RO-EmilNeural',
 'Russian (Russia)-Svetlana-Female': 'ru-RU-SvetlanaNeural',
 'Russian (Russia)-Dmitry-Male': 'ru-RU-DmitryNeural',
 'Sinhala (Sri Lanka)-Sameera-Male': 'si-LK-SameeraNeural',
 'Sinhala (Sri Lanka)-Thilini-Female': 'si-LK-ThiliniNeural',
 'Slovak (Slovakia)-Lukas-Male': 'sk-SK-LukasNeural',
 'Slovak (Slovakia)-Viktoria-Female': 'sk-SK-ViktoriaNeural',
 'Slovenian (Slovenia)-Petra-Female': 'sl-SI-PetraNeural',
 'Slovenian (Slovenia)-Rok-Male': 'sl-SI-RokNeural',
 'Somali (Somalia)-Muuse-Male': 'so-SO-MuuseNeural',
 'Somali (Somalia)-Ubax-Female': 'so-SO-UbaxNeural',
 'Albanian (Albania)-Anila-Female': 'sq-AL-AnilaNeural',
 'Albanian (Albania)-Ilir-Male': 'sq-AL-IlirNeural',
 'Serbian (Serbia)-Nicholas-Male': 'sr-RS-NicholasNeural',
 'Serbian (Serbia)-Sophie-Female': 'sr-RS-SophieNeural',
 'Sundanese (Indonesia)-Jajang-Male': 'su-ID-JajangNeural',
 'Sundanese (Indonesia)-Tuti-Female': 'su-ID-TutiNeural',
 'Swedish (Sweden)-Sofie-Female': 'sv-SE-SofieNeural',
 'Swedish (Sweden)-Mattias-Male': 'sv-SE-MattiasNeural',
 'Swahili (Kenya)-Rafiki-Male': 'sw-KE-RafikiNeural',
 'Swahili (Kenya)-Zuri-Female': 'sw-KE-ZuriNeural',
 'Swahili (Tanzania)-Daudi-Male': 'sw-TZ-DaudiNeural',
 'Swahili (Tanzania)-Rehema-Female': 'sw-TZ-RehemaNeural',
 'Tamil (India)-Pallavi-Female': 'ta-IN-PallaviNeural',
 'Tamil (India)-Valluvar-Male': 'ta-IN-ValluvarNeural',
 'Tamil (Sri Lanka)-Kumar-Male': 'ta-LK-KumarNeural',
 'Tamil (Sri Lanka)-Saranya-Female': 'ta-LK-SaranyaNeural',
 'Tamil (Malaysia)-Kani-Female': 'ta-MY-KaniNeural',
 'Tamil (Malaysia)-Surya-Male': 'ta-MY-SuryaNeural',
 'Tamil (Singapore)-Anbu-Male': 'ta-SG-AnbuNeural',
 'Telugu (India)-Mohan-Male': 'te-IN-MohanNeural',
 'Telugu (India)-Shruti-Female': 'te-IN-ShrutiNeural',
 'Thai (Thailand)-Premwadee-Female': 'th-TH-PremwadeeNeural',
 'Thai (Thailand)-Niwat-Male': 'th-TH-NiwatNeural',
 'Turkish (Turkey)-Ahmet-Male': 'tr-TR-AhmetNeural',
 'Turkish (Turkey)-Emel-Female': 'tr-TR-EmelNeural',
 'Ukrainian (Ukraine)-Ostap-Male': 'uk-UA-OstapNeural',
 'Ukrainian (Ukraine)-Polina-Female': 'uk-UA-PolinaNeural',
 'Urdu (India)-Gul-Female': 'ur-IN-GulNeural',
 'Urdu (India)-Salman-Male': 'ur-IN-SalmanNeural',
 'Urdu (Pakistan)-Asad-Male': 'ur-PK-AsadNeural',
 'Urdu (Pakistan)-Uzma-Female': 'ur-PK-UzmaNeural',
 'Uzbek (Uzbekistan)-Madina-Female': 'uz-UZ-MadinaNeural',
 'Uzbek (Uzbekistan)-Sardor-Male': 'uz-UZ-SardorNeural',
 'Vietnamese (Vietnam)-HoaiMy-Female': 'vi-VN-HoaiMyNeural',
 'Vietnamese (Vietnam)-NamMinh-Male': 'vi-VN-NamMinhNeural',
 'Chinese (Mandarin, Simplified)-Xiaoxiao-Female': 'zh-CN-XiaoxiaoNeural',
 'Chinese (Mandarin, Simplified)-Yunyang-Male': 'zh-CN-YunyangNeural',
 'Chinese (Mandarin, Simplified)-Yunxi-Male': 'zh-CN-YunxiNeural',
 'Chinese (Mandarin, Simplified)-Xiaoyi-Female': 'zh-CN-XiaoyiNeural',
 'Chinese (Mandarin, Simplified)-Yunjian-Male': 'zh-CN-YunjianNeural',
 'Chinese (Mandarin, Simplified)-Yunxia-Male': 'zh-CN-YunxiaNeural',
 'Chinese (Northeastern Mandarin, Simplified)-Xiaobei-Female': 'zh-CN-liaoning-XiaobeiNeural',
 'Chinese (Zhongyuan Mandarin Shaanxi, Simplified)-Xiaoni-Female': 'zh-CN-shaanxi-XiaoniNeural',
 'Chinese (Cantonese, Traditional)-HiuMaan-Female': 'zh-HK-HiuMaanNeural',
 'Chinese (Cantonese, Traditional)-HiuGaai-Female': 'zh-HK-HiuGaaiNeural',
 'Chinese (Cantonese, Traditional)-WanLung-Male': 'zh-HK-WanLungNeural',
 'Chinese (Taiwanese Mandarin)-HsiaoChen-Female': 'zh-TW-HsiaoChenNeural',
 'Chinese (Taiwanese Mandarin)-HsiaoYu-Female': 'zh-TW-HsiaoYuNeural',
 'Chinese (Taiwanese Mandarin)-YunJhe-Male': 'zh-TW-YunJheNeural',
 'Zulu (South Africa)-Thando-Female': 'zu-ZA-ThandoNeural',
 'Zulu (South Africa)-Themba-Male': 'zu-ZA-ThembaNeural'}




tts_fin = {
    "阿拉伯语 (南非)-Adri-女": "af-ZA-AdriNeural",
    "阿拉伯语 (南非)-Willem-男": "af-ZA-WillemNeural",
    "阿姆哈拉语 (埃塞俄比亚)-Ameha-男": "am-ET-AmehaNeural",
    "阿姆哈拉语 (埃塞俄比亚)-Mekdes-女": "am-ET-MekdesNeural",
    "阿拉伯语 (阿拉伯联合酋长国)-Fatima-女": "ar-AE-FatimaNeural",
    "阿拉伯语 (阿拉伯联合酋长国)-Hamdan-男": "ar-AE-HamdanNeural",
    "阿拉伯语 (巴林)-Ali-男": "ar-BH-AliNeural",
    "阿拉伯语 (巴林)-Laila-女": "ar-BH-LailaNeural",
    "阿拉伯语 (阿尔及利亚)-Ismael-男": "ar-DZ-IsmaelNeural",
    "阿拉伯语 (埃及)-Salma-女": "ar-EG-SalmaNeural",
    "阿拉伯语 (埃及)-Shakir-男": "ar-EG-ShakirNeural",
    "阿拉伯语 (伊拉克)-Bassel-男": "ar-IQ-BasselNeural",
    "阿拉伯语 (伊拉克)-Rana-女": "ar-IQ-RanaNeural",
    "阿拉伯语 (约旦)-Sana-女": "ar-JO-SanaNeural",
    "阿拉伯语 (约旦)-Taim-男": "ar-JO-TaimNeural",
    "阿拉伯语 (科威特)-Fahed-男": "ar-KW-FahedNeural",
    "阿拉伯语 (科威特)-Noura-女": "ar-KW-NouraNeural",
    "阿拉伯语 (黎巴嫩)-Layla-女": "ar-LB-LaylaNeural",
    "阿拉伯语 (黎巴嫩)-Rami-男": "ar-LB-RamiNeural",
    "阿拉伯语 (利比亚)-Iman-女": "ar-LY-ImanNeural",
    "阿拉伯语 (利比亚)-Omar-男": "ar-LY-OmarNeural",
    "阿拉伯语 (摩洛哥)-Jamal-男": "ar-MA-JamalNeural",
    "阿拉伯语 (摩洛哥)-Mouna-女": "ar-MA-MounaNeural",
    "阿拉伯语 (阿曼)-Abdullah-男": "ar-OM-AbdullahNeural",
    "阿拉伯语 (阿曼)-Aysha-女": "ar-OM-AyshaNeural",
    "阿拉伯语 (卡塔尔)-Amal-女": "ar-QA-AmalNeural",
    "阿拉伯语 (卡塔尔)-Moaz-男": "ar-QA-MoazNeural",
    "阿拉伯语 (沙特阿拉伯)-Hamed-男": "ar-SA-HamedNeural",
    "阿拉伯语 (沙特阿拉伯)-Zariyah-女": "ar-SA-ZariyahNeural",
    "阿拉伯语 (叙利亚)-Amany-女": "ar-SY-AmanyNeural",
    "阿拉伯语 (叙利亚)-Laith-男": "ar-SY-LaithNeural",
    "阿拉伯语 (突尼斯)-Hedi-男": "ar-TN-HediNeural",
    "阿拉伯语 (突尼斯)-Reem-女": "ar-TN-ReemNeural",
    "阿拉伯语 (也门)-Maryam-女": "ar-YE-MaryamNeural",
    "阿拉伯语 (也门)-Saleh-男": "ar-YE-SalehNeural",
    "阿塞拜疆语 (阿塞拜疆)-Babek-男": "az-AZ-BabekNeural",
    "阿塞拜疆语 (阿塞拜疆)-Banu-女": "az-AZ-BanuNeural",
    "保加利亚语 (保加利亚)-Borislav-男": "bg-BG-BorislavNeural",
    "保加利亚语 (保加利亚)-Kalina-女": "bg-BG-KalinaNeural",
    "孟加拉语 (孟加拉国)-Nabanita-女": "bn-BD-NabanitaNeural",
    "孟加拉语 (孟加拉国)-Pradeep-男": "bn-BD-PradeepNeural",
    "孟加拉语 (印度)-Bashkar-男": "bn-IN-BashkarNeural",
    "孟加拉语 (印度)-Tanishaa-女": "bn-IN-TanishaaNeural",
    "波斯尼亚语 (波斯尼亚和黑塞哥维那)-Goran-男": "bs-BA-GoranNeural",
    "波斯尼亚语 (波斯尼亚和黑塞哥维那)-Vesna-女": "bs-BA-VesnaNeural",
    "加泰罗尼亚语 (西班牙)-Joana-女": "ca-ES-JoanaNeural",
    "加泰罗尼亚语 (西班牙)-Enric-男": "ca-ES-EnricNeural",
    "捷克语 (捷克共和国)-Antonin-男": "cs-CZ-AntoninNeural",
    "捷克语 (捷克共和国)-Vlasta-女": "cs-CZ-VlastaNeural",
    "威尔士语 (英国)-Aled-男": "cy-GB-AledNeural",
    "威尔士语 (英国)-Nia-女": "cy-GB-NiaNeural",
    "丹麦语 (丹麦)-Christel-女": "da-DK-ChristelNeural",
    "丹麦语 (丹麦)-Jeppe-男": "da-DK-JeppeNeural",
    "德语 (奥地利)-Ingrid-女": "de-AT-IngridNeural",
    "德语 (奥地利)-Jonas-男": "de-AT-JonasNeural",
    "德语 (瑞士)-Jan-男": "de-CH-JanNeural",
    "德语 (瑞士)-Leni-女": "de-CH-LeniNeural",
    "德语 (德国)-Katja-女": "de-DE-KatjaNeural",
    "德语 (德国)-Amala-女": "de-DE-AmalaNeural",
    "德语 (德国)-Conrad-男": "de-DE-ConradNeural",
    "德语 (德国)-Killian-男": "de-DE-KillianNeural",
    "希腊语 (希腊)-Athina-女": "el-GR-AthinaNeural",
    "希腊语 (希腊)-Nestoras-男": "el-GR-NestorasNeural",
    "英语 (澳大利亚)-Natasha-女": "en-AU-NatashaNeural",
    "英语 (澳大利亚)-William-男": "en-AU-WilliamNeural",
    "英语 (加拿大)-Clara-女": "en-CA-ClaraNeural",
    "英语 (加拿大)-Liam-男": "en-CA-LiamNeural",
    "英语 (英国)-Libby-女": "en-GB-LibbyNeural",
    "英语 (英国)-Maisie-女": "en-GB-MaisieNeural",
    "英语 (英国)-Ryan-男": "en-GB-RyanNeural",
    "英语 (英国)-Sonia-女": "en-GB-SoniaNeural",
    "英语 (英国)-Thomas-男": "en-GB-ThomasNeural",
    "英语 (香港)-Sam-男": "en-HK-SamNeural",
    "英语 (香港)-Yan-女": "en-HK-YanNeural",
    "英语 (爱尔兰)-Connor-男": "en-IE-ConnorNeural",
    "英语 (爱尔兰)-Emily-女": "en-IE-EmilyNeural",
    "英语 (印度)-Neerja-女": "en-IN-NeerjaNeural",
    "英语 (印度)-Prabhat-男": "en-IN-PrabhatNeural",
    "英语 (肯尼亚)-Asilia-女": "en-KE-AsiliaNeural",
    "英语 (肯尼亚)-Chilemba-男": "en-KE-ChilembaNeural",
    "英语 (尼日利亚)-Abeo-男": "en-NG-AbeoNeural",
    "英语 (尼日利亚)-Ezinne-女": "en-NG-EzinneNeural",
    "英语 (新西兰)-Mitchell-男": "en-NZ-MitchellNeural",
    "英语 (菲律宾)-James-男": "en-PH-JamesNeural",
    "英语 (菲律宾)-Rosa-女": "en-PH-RosaNeural",
    "英语 (新加坡)-Luna-女": "en-SG-LunaNeural",
    "英语 (新加坡)-Wayne-男": "en-SG-WayneNeural",
    "英语 (坦桑尼亚)-Elimu-男": "en-TZ-ElimuNeural",
    "英语 (坦桑尼亚)-Imani-女": "en-TZ-ImaniNeural",
    "英语 (美国)-Jenny-女": "en-US-JennyNeural",
    "英语 (美国)-Guy-男": "en-US-GuyNeural",
    "英语 (美国)-Ana-女": "en-US-AnaNeural",
    "英语 (美国)-Aria-女": "en-US-AriaNeural",
    "英语 (美国)-Christopher-男": "en-US-ChristopherNeural",
    "英语 (美国)-Eric-男": "en-US-EricNeural",
    "英语 (美国)-Michelle-女": "en-US-MichelleNeural",
    "英语 (美国)-Roger-男": "en-US-RogerNeural",
    "英语 (南非)-Leah-女": "en-ZA-LeahNeural",
    "英语 (南非)-Luke-男": "en-ZA-LukeNeural",
    "西班牙语 (阿根廷)-Elena-女": "es-AR-ElenaNeural",
    "西班牙语 (阿根廷)-Tomas-男": "es-AR-TomasNeural",
    "西班牙语 (玻利维亚)-Marcelo-男": "es-BO-MarceloNeural",
    "西班牙语 (玻利维亚)-Sofia-女": "es-BO-SofiaNeural",
    "西班牙语 (哥伦比亚)-Gonzalo-男": "es-CO-GonzaloNeural",
    "西班牙语 (哥伦比亚)-Salome-女": "es-CO-SalomeNeural",
    "西班牙语 (哥斯达黎加)-Juan-男": "es-CR-JuanNeural",
    "西班牙语 (哥斯达黎加)-Maria-女": "es-CR-MariaNeural",
    "西班牙语 (古巴)-Belkys-女": "es-CU-BelkysNeural",
    "西班牙语 (多米尼加共和国)-Emilio-男": "es-DO-EmilioNeural",
    "西班牙语 (多米尼加共和国)-Ramona-女": "es-DO-RamonaNeural",
    "西班牙语 (厄瓜多尔)-Andrea-女": "es-EC-AndreaNeural",
    "西班牙语 (厄瓜多尔)-Luis-男": "es-EC-LuisNeural",
    "西班牙语 (西班牙)-Alvaro-男": "es-ES-AlvaroNeural",
    "西班牙语 (西班牙)-Elvira-女": "es-ES-ElviraNeural",
    "西班牙语 (赤道几内亚)-Teresa-女": "es-GQ-TeresaNeural",
    "西班牙语 (危地马拉)-Andres-男": "es-GT-AndresNeural",
    "西班牙语 (危地马拉)-Marta-女": "es-GT-MartaNeural",
    "西班牙语 (洪都拉斯)-Carlos-男": "es-HN-CarlosNeural",
    "西班牙语 (洪都拉斯)-Karla-女": "es-HN-KarlaNeural",
    "西班牙语 (墨西哥)-Dalia-女": "es-MX-DaliaNeural",
    "西班牙语 (墨西哥)-Jorge-男": "es-MX-JorgeNeural",
    "西班牙语 (尼加拉瓜)-Federico-男": "es-NI-FedericoNeural",
    "西班牙语 (尼加拉瓜)-Yolanda-女": "es-NI-YolandaNeural",
    "西班牙语 (巴拿马)-Margarita-女": "es-PA-MargaritaNeural",
    "西班牙语 (巴拿马)-Roberto-男": "es-PA-RobertoNeural",
    "西班牙语 (秘鲁)-Alex-男": "es-PE-AlexNeural",
    "西班牙语 (秘鲁)-Camila-女": "es-PE-CamilaNeural",
    "西班牙语 (波多黎各)-Karina-女": "es-PR-KarinaNeural",
    "西班牙语 (波多黎各)-Victor-男": "es-PR-VictorNeural",
    "西班牙语 (巴拉圭)-Mario-男": "es-PY-MarioNeural",
    "西班牙语 (巴拉圭)-Tania-女": "es-PY-TaniaNeural",
    "西班牙语 (萨尔瓦多)-Lorena-女": "es-SV-LorenaNeural",
    "西班牙语 (萨尔瓦多)-Rodrigo-男": "es-SV-RodrigoNeural",
    "西班牙语 (美国)-Alonso-男": "es-US-AlonsoNeural",
    "西班牙语 (美国)-Paloma-女": "es-US-PalomaNeural",
    "西班牙语 (乌拉圭)-Mateo-男": "es-UY-MateoNeural",
    "西班牙语 (乌拉圭)-Valentina-女": "es-UY-ValentinaNeural",
    "西班牙语 (委内瑞拉)-Paola-女": "es-VE-PaolaNeural",
    "西班牙语 (委内瑞拉)-Sebastian-男": "es-VE-SebastianNeural",
    "爱沙尼亚语 (爱沙尼亚)-Anu-女": "et-EE-AnuNeural",
    "爱沙尼亚语 (爱沙尼亚)-Kert-男": "et-EE-KertNeural",
    "波斯语 (伊朗)-Dilara-女": "fa-IR-DilaraNeural",
    "波斯语 (伊朗)-Farid-男": "fa-IR-FaridNeural",
    "芬兰语 (芬兰)-Harri-男": "fi-FI-HarriNeural",
    "芬兰语 (芬兰)-Noora-女": "fi-FI-NooraNeural",
    "法语 (比利时)-Charline-女": "fr-BE-CharlineNeural",
    "法语 (比利时)-Gerard-男": "fr-BE-GerardNeural",
    "法语 (加拿大)-Sylvie-女": "fr-CA-SylvieNeural",
    "法语 (加拿大)-Antoine-男": "fr-CA-AntoineNeural",
    "法语 (加拿大)-Jean-男": "fr-CA-JeanNeural",
    "法语 (瑞士)-Ariane-女": "fr-CH-ArianeNeural",
    "法语 (瑞士)-Fabrice-男": "fr-CH-FabriceNeural",
    "法语 (法国)-Denise-女": "fr-FR-DeniseNeural",
    "法语 (法国)-Eloise-女": "fr-FR-EloiseNeural",
    "法语 (法国)-Henri-男": "fr-FR-HenriNeural",
    "爱尔兰语 (爱尔兰)-Colm-男": "ga-IE-ColmNeural",
    "爱尔兰语 (爱尔兰)-Orla-女": "ga-IE-OrlaNeural",
    "加利西亚语 (西班牙)-Roi-男": "gl-ES-RoiNeural",
    "加利西亚语 (西班牙)-Sabela-女": "gl-ES-SabelaNeural",
    "古吉拉特语 (印度)-Dhwani-女": "gu-IN-DhwaniNeural",
    "古吉拉特语 (印度)-Niranjan-男": "gu-IN-NiranjanNeural",
    "希伯来语 (以色列)-Avri-男": "he-IL-AvriNeural",
    "希伯来语 (以色列)-Hila-女": "he-IL-HilaNeural",
    "印地语 (印度)-Madhur-男": "hi-IN-MadhurNeural",
    "印地语 (印度)-Swara-女": "hi-IN-SwaraNeural",
    "克罗地亚语 (克罗地亚)-Gabrijela-女": "hr-HR-GabrijelaNeural",
    "克罗地亚语 (克罗地亚)-Srecko-男": "hr-HR-SreckoNeural",
    "匈牙利语 (匈牙利)-Noemi-女": "hu-HU-NoemiNeural",
    "匈牙利语 (匈牙利)-Tamas-男": "hu-HU-TamasNeural",
    "印度尼西亚语 (印度尼西亚)-Ardi-男": "id-ID-ArdiNeural",
    "印度尼西亚语 (印度尼西亚)-Gadis-女": "id-ID-GadisNeural",
    "冰岛语 (冰岛)-Gudrun-女": "is-IS-GudrunNeural",
    "冰岛语 (冰岛)-Gunnar-男": "is-IS-GunnarNeural",
    "意大利语 (意大利)-Isabella-女": "it-IT-IsabellaNeural",
    "意大利语 (意大利)-Diego-男": "it-IT-DiegoNeural",
    "意大利语 (意大利)-Elsa-女": "it-IT-ElsaNeural",
    "日语 (日本)-Nanami-女": "ja-JP-NanamiNeural",
    "日语 (日本)-Keita-男": "ja-JP-KeitaNeural",
    "爪哇语 (印度尼西亚)-Dimas-男": "jv-ID-DimasNeural",
    "爪哇语 (印度尼西亚)-Siti-女": "jv-ID-SitiNeural",
    "格鲁吉亚语 (格鲁吉亚)-Eka-女": "ka-GE-EkaNeural",
    "格鲁吉亚语 (格鲁吉亚)-Giorgi-男": "ka-GE-GiorgiNeural",
    "哈萨克语 (哈萨克斯坦)-Aigul-女": "kk-KZ-AigulNeural",
    "哈萨克语 (哈萨克斯坦)-Daulet-男": "kk-KZ-DauletNeural",
    "高棉语 (柬埔寨)-Piseth-男": "km-KH-PisethNeural",
    "高棉语 (柬埔寨)-Sreymom-女": "km-KH-SreymomNeural",
    "卡纳达语 (印度)-Gagan-男": "kn-IN-GaganNeural",
    "卡纳达语 (印度)-Sapna-女": "kn-IN-SapnaNeural",
    "韩语 (韩国)-Sun-Hi-女": "ko-KR-SunHiNeural",
    "韩语 (韩国)-InJoon-男": "ko-KR-InJoonNeural",
    "老挝语 (老挝)-Chanthavong-男": "lo-LA-ChanthavongNeural",
    "老挝语 (老挝)-Keomany-女": "lo-LA-KeomanyNeural",
    "立陶宛语 (立陶宛)-Leonas-男": "lt-LT-LeonasNeural",
    "立陶宛语 (立陶宛)-Ona-女": "lt-LT-OnaNeural",
    "拉脱维亚语 (拉脱维亚)-Everita-女": "lv-LV-EveritaNeural",
    "拉脱维亚语 (拉脱维亚)-Nils-男": "lv-LV-NilsNeural",
    "马其顿语 (北马其顿共和国)-Aleksandar-男": "mk-MK-AleksandarNeural",
    "马其顿语 (北马其顿共和国)-Marija-女": "mk-MK-MarijaNeural",
    "马拉雅拉姆语 (印度)-Midhun-男": "ml-IN-MidhunNeural",
    "马拉雅拉姆语 (印度)-Sobhana-女": "ml-IN-SobhanaNeural",
    "蒙古语 (蒙古)-Bataa-男": "mn-MN-BataaNeural",
    "蒙古语 (蒙古)-Yesui-女": "mn-MN-YesuiNeural",
    "马拉地语 (印度)-Aarohi-女": "mr-IN-AarohiNeural",
    "马拉地语 (印度)-Manohar-男": "mr-IN-ManoharNeural",
    "马来语 (马来西亚)-Osman-男": "ms-MY-OsmanNeural",
    "马来语 (马来西亚)-Yasmin-女": "ms-MY-YasminNeural",
    "马耳他语 (马耳他)-Grace-女": "mt-MT-GraceNeural",
    "马耳他语 (马耳他)-Joseph-男": "mt-MT-JosephNeural",
    "缅甸语 (缅甸)-Nilar-女": "my-MM-NilarNeural",
    "缅甸语 (缅甸)-Thiha-男": "my-MM-ThihaNeural",
    "挪威语 (挪威)-Pernille-女": "nb-NO-PernilleNeural",
    "挪威语 (挪威)-Finn-男": "nb-NO-FinnNeural",
    "尼泊尔语 (尼泊尔)-Hemkala-女": "ne-NP-HemkalaNeural",
    "尼泊尔语 (尼泊尔)-Sagar-男": "ne-NP-SagarNeural",
    "荷兰语 (比利时)-Arnaud-男": "nl-BE-ArnaudNeural",
    "荷兰语 (比利时)-Dena-女": "nl-BE-DenaNeural",
    "荷兰语 (荷兰)-Colette-女": "nl-NL-ColetteNeural",
    "荷兰语 (荷兰)-Fenna-女": "nl-NL-FennaNeural",
    "荷兰语 (荷兰)-Maarten-男": "nl-NL-MaartenNeural",
    "波兰语 (波兰)-Marek-男": "pl-PL-MarekNeural",
    "波兰语 (波兰)-Zofia-女": "pl-PL-ZofiaNeural",
    "普什图语 (阿富汗)-Gul Nawaz-男": "ps-AF-GulNawazNeural",
    "普什图语 (阿富汗)-Latifa-女": "ps-AF-LatifaNeural",
    "葡萄牙语 (巴西)-Francisca-女": "pt-BR-FranciscaNeural",
    "葡萄牙语 (巴西)-Antonio-男": "pt-BR-AntonioNeural",
    "葡萄牙语 (葡萄牙)-Duarte-男": "pt-PT-DuarteNeural",
    "葡萄牙语 (葡萄牙)-Raquel-女": "pt-PT-RaquelNeural",
    "罗马尼亚语 (罗马尼亚)-Alina-女": "ro-RO-AlinaNeural",
    "罗马尼亚语 (罗马尼亚)-Emil-男": "ro-RO-EmilNeural",
    "俄语 (俄罗斯)-Svetlana-女": "ru-RU-SvetlanaNeural",
    "俄语 (俄罗斯)-Dmitry-男": "ru-RU-DmitryNeural",
    "僧伽罗语 (斯里兰卡)-Sameera-男": "si-LK-SameeraNeural",
    "僧伽罗语 (斯里兰卡)-Thilini-女": "si-LK-ThiliniNeural",
    "斯洛伐克语 (斯洛伐克)-Lukas-男": "sk-SK-LukasNeural",
    "斯洛伐克语 (斯洛伐克)-Viktoria-女":"sk-SK-ViktoriaNeural",
    "斯洛文尼亚语 (斯洛文尼亚)-Petra-女": "sl-SI-PetraNeural",
    "斯洛文尼亚语 (斯洛文尼亚)-Rok-男": "sl-SI-RokNeural",
    "索马里语 (索马里)-Muuse-男": "so-SO-MuuseNeural",
    "索马里语 (索马里)-Ubax-女": "so-SO-UbaxNeural",
    "阿尔巴尼亚语 (阿尔巴尼亚)-Anila-女": "sq-AL-AnilaNeural",
    "阿尔巴尼亚语 (阿尔巴尼亚)-Ilir-男": "sq-AL-IlirNeural",
    "塞尔维亚语 (塞尔维亚)-Nicholas-男": "sr-RS-NicholasNeural",
    "塞尔维亚语 (塞尔维亚)-Sophie-女": "sr-RS-SophieNeural",
    "巽他语 (印度尼西亚)-Jajang-男": "su-ID-JajangNeural",
    "巽他语 (印度尼西亚)-Tuti-女": "su-ID-TutiNeural",
    "瑞典语 (瑞典)-Sofie-女": "sv-SE-SofieNeural",
    "瑞典语 (瑞典)-Mattias-男": "sv-SE-MattiasNeural",
    "斯瓦希里语 (肯尼亚)-Rafiki-男": "sw-KE-RafikiNeural",
    "斯瓦希里语 (肯尼亚)-Zuri-女": "sw-KE-ZuriNeural",
    "斯瓦希里语 (坦桑尼亚)-Daudi-男": "sw-TZ-DaudiNeural",
    "斯瓦希里语 (坦桑尼亚)-Rehema-女": "sw-TZ-RehemaNeural",
    "泰米尔语 (印度)-Pallavi-女": "ta-IN-PallaviNeural",
    "泰米尔语 (印度)-Valluvar-男": "ta-IN-ValluvarNeural",
    "泰米尔语 (斯里兰卡)-Kumar-男": "ta-LK-KumarNeural",
    "泰米尔语 (斯里兰卡)-Saranya-女": "ta-LK-SaranyaNeural",
    "泰米尔语 (马来西亚)-Kani-女": "ta-MY-KaniNeural",
    "泰米尔语 (马来西亚)-Surya-男": "ta-MY-SuryaNeural",
    "泰米尔语 (新加坡)-Anbu-男": "ta-SG-AnbuNeural",
    "泰卢固语 (印度)-Mohan-男": "te-IN-MohanNeural",
    "泰卢固语 (印度)-Shruti-女": "te-IN-ShrutiNeural",
    "泰语 (泰国)-Premwadee-女": "th-TH-PremwadeeNeural",
    "泰语 (泰国)-Niwat-男": "th-TH-NiwatNeural",
    "土耳其语 (土耳其)-Ahmet-男": "tr-TR-AhmetNeural",
    "土耳其语 (土耳其)-Emel-女": "tr-TR-EmelNeural",
    "乌克兰语 (乌克兰)-Ostap-男": "uk-UA-OstapNeural",
    "乌克兰语 (乌克兰)-Polina-女": "uk-UA-PolinaNeural",
    "乌尔都语 (印度)-Gul-女": "ur-IN-GulNeural",
    "乌尔都语 (印度)-Salman-男": "ur-IN-SalmanNeural",
    "乌尔都语 (巴基斯坦)-Asad-男": "ur-PK-AsadNeural",
    "乌尔都语 (巴基斯坦)-Uzma-女": "ur-PK-UzmaNeural",
    "乌兹别克语 (乌兹别克斯坦)-Madina-女": "uz-UZ-MadinaNeural",
    "乌兹别克语 (乌兹别克斯坦)-Sardor-男": "uz-UZ-SardorNeural",
    "越南语 (越南)-HoaiMy-女": "vi-VN-HoaiMyNeural",
    "越南语 (越南)-NamMinh-男": "vi-VN-NamMinhNeural",
    "普通话 (中国大陆)-Xiaoxiao-女": "zh-CN-XiaoxiaoNeural",
    "普通话 (中国大陆)-Yunyang-男": "zh-CN-YunyangNeural",
    "普通话 (中国大陆)-Yunxi-男": "zh-CN-YunxiNeural",
    "普通话 (中国大陆)-Xiaoyi-女": "zh-CN-XiaoyiNeural",
    "普通话 (中国大陆)-Yunjian-男": "zh-CN-YunjianNeural",
    "普通话 (中国大陆)-Yunxia-男": "zh-CN-YunxiaNeural",
    "东北话 (中国大陆)-Xiaobei-女": "zh-CN-liaoning-XiaobeiNeural",
    "中原官话 (中国陕西)-Xiaoni-女": "zh-CN-shaanxi-XiaoniNeural",
    "粤语 (中国香港)-HiuMaan-女": "zh-HK-HiuMaanNeural",
    "粤语 (中国香港)-HiuGaai-女": "zh-HK-HiuGaaiNeural",
    "粤语 (中国香港)-WanLung-男": "zh-HK-WanLungNeural",
    "台湾普通话-HsiaoChen-女": "zh-TW-HsiaoChenNeural",
    "台湾普通话-HsiaoYu-女": "zh-TW-HsiaoYuNeural",
    "台湾普通话-YunJhe-男": "zh-TW-YunJheNeural",
    "祖鲁语 (南非)-Thando-女": "zu-ZA-ThandoNeural",
    "祖鲁语 (南非)-Themba-男": "zu-ZA-ThembaNeural"}



tts_order_voice = {'普通话 (中国大陆)-Xiaoxiao-女': 'zh-CN-XiaoxiaoNeural',
 '普通话 (中国大陆)-Yunyang-男': 'zh-CN-YunyangNeural',
 '普通话 (中国大陆)-Yunxi-男': 'zh-CN-YunxiNeural',
 '普通话 (中国大陆)-Xiaoyi-女': 'zh-CN-XiaoyiNeural',
 '普通话 (中国大陆)-Yunjian-男': 'zh-CN-YunjianNeural',
 '普通话 (中国大陆)-Yunxia-男': 'zh-CN-YunxiaNeural',
 '东北话 (中国大陆)-Xiaobei-女': 'zh-CN-liaoning-XiaobeiNeural',
 '中原官话 (中国陕西)-Xiaoni-女': 'zh-CN-shaanxi-XiaoniNeural',
 '粤语 (中国香港)-HiuMaan-女': 'zh-HK-HiuMaanNeural',
 '粤语 (中国香港)-HiuGaai-女': 'zh-HK-HiuGaaiNeural',
 '粤语 (中国香港)-WanLung-男': 'zh-HK-WanLungNeural',
 '台湾普通话-HsiaoChen-女': 'zh-TW-HsiaoChenNeural',
 '台湾普通话-HsiaoYu-女': 'zh-TW-HsiaoYuNeural',
 '台湾普通话-YunJhe-男': 'zh-TW-YunJheNeural',
    '英语 (美国)-Jenny-女': 'en-US-JennyNeural',
 '英语 (美国)-Guy-男': 'en-US-GuyNeural',
 '英语 (美国)-Ana-女': 'en-US-AnaNeural',
 '英语 (美国)-Aria-女': 'en-US-AriaNeural',
 '英语 (美国)-Christopher-男': 'en-US-ChristopherNeural',
 '英语 (美国)-Eric-男': 'en-US-EricNeural',
 '英语 (美国)-Michelle-女': 'en-US-MichelleNeural',
 '英语 (美国)-Roger-男': 'en-US-RogerNeural',
 '西班牙语 (墨西哥)-Dalia-女': 'es-MX-DaliaNeural',
 '西班牙语 (墨西哥)-Jorge-男': 'es-MX-JorgeNeural',
 '韩语 (韩国)-Sun-Hi-女': 'ko-KR-SunHiNeural',
 '韩语 (韩国)-InJoon-男': 'ko-KR-InJoonNeural',
'泰语 (泰国)-Premwadee-女': 'th-TH-PremwadeeNeural',
 '泰语 (泰国)-Niwat-男': 'th-TH-NiwatNeural',
 '越南语 (越南)-HoaiMy-女': 'vi-VN-HoaiMyNeural',
'越南语 (越南)-NamMinh-男': 'vi-VN-NamMinhNeural',
 '日语 (日本)-Nanami-女': 'ja-JP-NanamiNeural',
 '日语 (日本)-Keita-男': 'ja-JP-KeitaNeural',
 '法语 (法国)-Denise-女': 'fr-FR-DeniseNeural',
 '法语 (法国)-Eloise-女': 'fr-FR-EloiseNeural',
 '法语 (法国)-Henri-男': 'fr-FR-HenriNeural',
 '葡萄牙语 (巴西)-Francisca-女': 'pt-BR-FranciscaNeural',
 '葡萄牙语 (巴西)-Antonio-男': 'pt-BR-AntonioNeural',
 '印度尼西亚语 (印度尼西亚)-Ardi-男': 'id-ID-ArdiNeural',
 '印度尼西亚语 (印度尼西亚)-Gadis-女': 'id-ID-GadisNeural',
 '希伯来语 (以色列)-Avri-男': 'he-IL-AvriNeural',
 '希伯来语 (以色列)-Hila-女': 'he-IL-HilaNeural',
'意大利语 (意大利)-Isabella-女': 'it-IT-IsabellaNeural',
 '意大利语 (意大利)-Diego-男': 'it-IT-DiegoNeural',
 '意大利语 (意大利)-Elsa-女': 'it-IT-ElsaNeural',
 '荷兰语 (荷兰)-Colette-女': 'nl-NL-ColetteNeural',
 '荷兰语 (荷兰)-Fenna-女': 'nl-NL-FennaNeural',
 '荷兰语 (荷兰)-Maarten-男': 'nl-NL-MaartenNeural',
'马来语 (马来西亚)-Osman-男': 'ms-MY-OsmanNeural',
 '马来语 (马来西亚)-Yasmin-女': 'ms-MY-YasminNeural',
 '挪威语 (挪威)-Pernille-女': 'nb-NO-PernilleNeural',
 '挪威语 (挪威)-Finn-男': 'nb-NO-FinnNeural',
 '瑞典语 (瑞典)-Sofie-女': 'sv-SE-SofieNeural',
 '瑞典语 (瑞典)-Mattias-男': 'sv-SE-MattiasNeural',
 '阿拉伯语 (沙特阿拉伯)-Hamed-男': 'ar-SA-HamedNeural',
 '阿拉伯语 (沙特阿拉伯)-Zariyah-女': 'ar-SA-ZariyahNeural',
 '希腊语 (希腊)-Athina-女': 'el-GR-AthinaNeural',
 '希腊语 (希腊)-Nestoras-男': 'el-GR-NestorasNeural',
'德语 (德国)-Katja-女': 'de-DE-KatjaNeural',
 '德语 (德国)-Amala-女': 'de-DE-AmalaNeural',
 '德语 (德国)-Conrad-男': 'de-DE-ConradNeural',
 '德语 (德国)-Killian-男': 'de-DE-KillianNeural',
 '阿拉伯语 (南非)-Adri-女': 'af-ZA-AdriNeural',
 '阿拉伯语 (南非)-Willem-男': 'af-ZA-WillemNeural',
 '阿姆哈拉语 (埃塞俄比亚)-Ameha-男': 'am-ET-AmehaNeural',
 '阿姆哈拉语 (埃塞俄比亚)-Mekdes-女': 'am-ET-MekdesNeural',
 '阿拉伯语 (阿拉伯联合酋长国)-Fatima-女': 'ar-AE-FatimaNeural',
 '阿拉伯语 (阿拉伯联合酋长国)-Hamdan-男': 'ar-AE-HamdanNeural',
 '阿拉伯语 (巴林)-Ali-男': 'ar-BH-AliNeural',
 '阿拉伯语 (巴林)-Laila-女': 'ar-BH-LailaNeural',
 '阿拉伯语 (阿尔及利亚)-Ismael-男': 'ar-DZ-IsmaelNeural',
 '阿拉伯语 (埃及)-Salma-女': 'ar-EG-SalmaNeural',
 '阿拉伯语 (埃及)-Shakir-男': 'ar-EG-ShakirNeural',
 '阿拉伯语 (伊拉克)-Bassel-男': 'ar-IQ-BasselNeural',
 '阿拉伯语 (伊拉克)-Rana-女': 'ar-IQ-RanaNeural',
 '阿拉伯语 (约旦)-Sana-女': 'ar-JO-SanaNeural',
 '阿拉伯语 (约旦)-Taim-男': 'ar-JO-TaimNeural',
 '阿拉伯语 (科威特)-Fahed-男': 'ar-KW-FahedNeural',
 '阿拉伯语 (科威特)-Noura-女': 'ar-KW-NouraNeural',
 '阿拉伯语 (黎巴嫩)-Layla-女': 'ar-LB-LaylaNeural',
 '阿拉伯语 (黎巴嫩)-Rami-男': 'ar-LB-RamiNeural',
 '阿拉伯语 (利比亚)-Iman-女': 'ar-LY-ImanNeural',
 '阿拉伯语 (利比亚)-Omar-男': 'ar-LY-OmarNeural',
 '阿拉伯语 (摩洛哥)-Jamal-男': 'ar-MA-JamalNeural',
 '阿拉伯语 (摩洛哥)-Mouna-女': 'ar-MA-MounaNeural',
 '阿拉伯语 (阿曼)-Abdullah-男': 'ar-OM-AbdullahNeural',
 '阿拉伯语 (阿曼)-Aysha-女': 'ar-OM-AyshaNeural',
 '阿拉伯语 (卡塔尔)-Amal-女': 'ar-QA-AmalNeural',
 '阿拉伯语 (卡塔尔)-Moaz-男': 'ar-QA-MoazNeural',
 '阿拉伯语 (叙利亚)-Amany-女': 'ar-SY-AmanyNeural',
 '阿拉伯语 (叙利亚)-Laith-男': 'ar-SY-LaithNeural',
 '阿拉伯语 (突尼斯)-Hedi-男': 'ar-TN-HediNeural',
 '阿拉伯语 (突尼斯)-Reem-女': 'ar-TN-ReemNeural',
 '阿拉伯语 (也门)-Maryam-女': 'ar-YE-MaryamNeural',
 '阿拉伯语 (也门)-Saleh-男': 'ar-YE-SalehNeural',
 '阿塞拜疆语 (阿塞拜疆)-Babek-男': 'az-AZ-BabekNeural',
 '阿塞拜疆语 (阿塞拜疆)-Banu-女': 'az-AZ-BanuNeural',
 '保加利亚语 (保加利亚)-Borislav-男': 'bg-BG-BorislavNeural',
 '保加利亚语 (保加利亚)-Kalina-女': 'bg-BG-KalinaNeural',
 '孟加拉语 (孟加拉国)-Nabanita-女': 'bn-BD-NabanitaNeural',
 '孟加拉语 (孟加拉国)-Pradeep-男': 'bn-BD-PradeepNeural',
 '孟加拉语 (印度)-Bashkar-男': 'bn-IN-BashkarNeural',
 '孟加拉语 (印度)-Tanishaa-女': 'bn-IN-TanishaaNeural',
 '波斯尼亚语 (波斯尼亚和黑塞哥维那)-Goran-男': 'bs-BA-GoranNeural',
 '波斯尼亚语 (波斯尼亚和黑塞哥维那)-Vesna-女': 'bs-BA-VesnaNeural',
 '加泰罗尼亚语 (西班牙)-Joana-女': 'ca-ES-JoanaNeural',
 '加泰罗尼亚语 (西班牙)-Enric-男': 'ca-ES-EnricNeural',
 '捷克语 (捷克共和国)-Antonin-男': 'cs-CZ-AntoninNeural',
 '捷克语 (捷克共和国)-Vlasta-女': 'cs-CZ-VlastaNeural',
 '威尔士语 (英国)-Aled-男': 'cy-GB-AledNeural',
 '威尔士语 (英国)-Nia-女': 'cy-GB-NiaNeural',
 '丹麦语 (丹麦)-Christel-女': 'da-DK-ChristelNeural',
 '丹麦语 (丹麦)-Jeppe-男': 'da-DK-JeppeNeural',
 '德语 (奥地利)-Ingrid-女': 'de-AT-IngridNeural',
 '德语 (奥地利)-Jonas-男': 'de-AT-JonasNeural',
 '德语 (瑞士)-Jan-男': 'de-CH-JanNeural',
 '德语 (瑞士)-Leni-女': 'de-CH-LeniNeural',
 '英语 (澳大利亚)-Natasha-女': 'en-AU-NatashaNeural',
 '英语 (澳大利亚)-William-男': 'en-AU-WilliamNeural',
 '英语 (加拿大)-Clara-女': 'en-CA-ClaraNeural',
 '英语 (加拿大)-Liam-男': 'en-CA-LiamNeural',
 '英语 (英国)-Libby-女': 'en-GB-LibbyNeural',
 '英语 (英国)-Maisie-女': 'en-GB-MaisieNeural',
 '英语 (英国)-Ryan-男': 'en-GB-RyanNeural',
 '英语 (英国)-Sonia-女': 'en-GB-SoniaNeural',
 '英语 (英国)-Thomas-男': 'en-GB-ThomasNeural',
 '英语 (香港)-Sam-男': 'en-HK-SamNeural',
 '英语 (香港)-Yan-女': 'en-HK-YanNeural',
 '英语 (爱尔兰)-Connor-男': 'en-IE-ConnorNeural',
 '英语 (爱尔兰)-Emily-女': 'en-IE-EmilyNeural',
 '英语 (印度)-Neerja-女': 'en-IN-NeerjaNeural',
 '英语 (印度)-Prabhat-男': 'en-IN-PrabhatNeural',
 '英语 (肯尼亚)-Asilia-女': 'en-KE-AsiliaNeural',
 '英语 (肯尼亚)-Chilemba-男': 'en-KE-ChilembaNeural',
 '英语 (尼日利亚)-Abeo-男': 'en-NG-AbeoNeural',
 '英语 (尼日利亚)-Ezinne-女': 'en-NG-EzinneNeural',
 '英语 (新西兰)-Mitchell-男': 'en-NZ-MitchellNeural',
 '英语 (菲律宾)-James-男': 'en-PH-JamesNeural',
 '英语 (菲律宾)-Rosa-女': 'en-PH-RosaNeural',
 '英语 (新加坡)-Luna-女': 'en-SG-LunaNeural',
 '英语 (新加坡)-Wayne-男': 'en-SG-WayneNeural',
 '英语 (坦桑尼亚)-Elimu-男': 'en-TZ-ElimuNeural',
 '英语 (坦桑尼亚)-Imani-女': 'en-TZ-ImaniNeural',
 '英语 (南非)-Leah-女': 'en-ZA-LeahNeural',
 '英语 (南非)-Luke-男': 'en-ZA-LukeNeural',
 '西班牙语 (阿根廷)-Elena-女': 'es-AR-ElenaNeural',
 '西班牙语 (阿根廷)-Tomas-男': 'es-AR-TomasNeural',
 '西班牙语 (玻利维亚)-Marcelo-男': 'es-BO-MarceloNeural',
 '西班牙语 (玻利维亚)-Sofia-女': 'es-BO-SofiaNeural',
 '西班牙语 (哥伦比亚)-Gonzalo-男': 'es-CO-GonzaloNeural',
 '西班牙语 (哥伦比亚)-Salome-女': 'es-CO-SalomeNeural',
 '西班牙语 (哥斯达黎加)-Juan-男': 'es-CR-JuanNeural',
 '西班牙语 (哥斯达黎加)-Maria-女': 'es-CR-MariaNeural',
 '西班牙语 (古巴)-Belkys-女': 'es-CU-BelkysNeural',
 '西班牙语 (多米尼加共和国)-Emilio-男': 'es-DO-EmilioNeural',
 '西班牙语 (多米尼加共和国)-Ramona-女': 'es-DO-RamonaNeural',
 '西班牙语 (厄瓜多尔)-Andrea-女': 'es-EC-AndreaNeural',
 '西班牙语 (厄瓜多尔)-Luis-男': 'es-EC-LuisNeural',
 '西班牙语 (西班牙)-Alvaro-男': 'es-ES-AlvaroNeural',
 '西班牙语 (西班牙)-Elvira-女': 'es-ES-ElviraNeural',
 '西班牙语 (赤道几内亚)-Teresa-女': 'es-GQ-TeresaNeural',
 '西班牙语 (危地马拉)-Andres-男': 'es-GT-AndresNeural',
 '西班牙语 (危地马拉)-Marta-女': 'es-GT-MartaNeural',
 '西班牙语 (洪都拉斯)-Carlos-男': 'es-HN-CarlosNeural',
 '西班牙语 (洪都拉斯)-Karla-女': 'es-HN-KarlaNeural',
 '西班牙语 (尼加拉瓜)-Federico-男': 'es-NI-FedericoNeural',
 '西班牙语 (尼加拉瓜)-Yolanda-女': 'es-NI-YolandaNeural',
 '西班牙语 (巴拿马)-Margarita-女': 'es-PA-MargaritaNeural',
 '西班牙语 (巴拿马)-Roberto-男': 'es-PA-RobertoNeural',
 '西班牙语 (秘鲁)-Alex-男': 'es-PE-AlexNeural',
 '西班牙语 (秘鲁)-Camila-女': 'es-PE-CamilaNeural',
 '西班牙语 (波多黎各)-Karina-女': 'es-PR-KarinaNeural',
 '西班牙语 (波多黎各)-Victor-男': 'es-PR-VictorNeural',
 '西班牙语 (巴拉圭)-Mario-男': 'es-PY-MarioNeural',
 '西班牙语 (巴拉圭)-Tania-女': 'es-PY-TaniaNeural',
 '西班牙语 (萨尔瓦多)-Lorena-女': 'es-SV-LorenaNeural',
 '西班牙语 (萨尔瓦多)-Rodrigo-男': 'es-SV-RodrigoNeural',
 '西班牙语 (美国)-Alonso-男': 'es-US-AlonsoNeural',
 '西班牙语 (美国)-Paloma-女': 'es-US-PalomaNeural',
 '西班牙语 (乌拉圭)-Mateo-男': 'es-UY-MateoNeural',
 '西班牙语 (乌拉圭)-Valentina-女': 'es-UY-ValentinaNeural',
 '西班牙语 (委内瑞拉)-Paola-女': 'es-VE-PaolaNeural',
 '西班牙语 (委内瑞拉)-Sebastian-男': 'es-VE-SebastianNeural',
 '爱沙尼亚语 (爱沙尼亚)-Anu-女': 'et-EE-AnuNeural',
 '爱沙尼亚语 (爱沙尼亚)-Kert-男': 'et-EE-KertNeural',
 '波斯语 (伊朗)-Dilara-女': 'fa-IR-DilaraNeural',
 '波斯语 (伊朗)-Farid-男': 'fa-IR-FaridNeural',
 '芬兰语 (芬兰)-Harri-男': 'fi-FI-HarriNeural',
 '芬兰语 (芬兰)-Noora-女': 'fi-FI-NooraNeural',
 '法语 (比利时)-Charline-女': 'fr-BE-CharlineNeural',
 '法语 (比利时)-Gerard-男': 'fr-BE-GerardNeural',
 '法语 (加拿大)-Sylvie-女': 'fr-CA-SylvieNeural',
 '法语 (加拿大)-Antoine-男': 'fr-CA-AntoineNeural',
 '法语 (加拿大)-Jean-男': 'fr-CA-JeanNeural',
 '法语 (瑞士)-Ariane-女': 'fr-CH-ArianeNeural',
 '法语 (瑞士)-Fabrice-男': 'fr-CH-FabriceNeural',
 '爱尔兰语 (爱尔兰)-Colm-男': 'ga-IE-ColmNeural',
 '爱尔兰语 (爱尔兰)-Orla-女': 'ga-IE-OrlaNeural',
 '加利西亚语 (西班牙)-Roi-男': 'gl-ES-RoiNeural',
 '加利西亚语 (西班牙)-Sabela-女': 'gl-ES-SabelaNeural',
 '古吉拉特语 (印度)-Dhwani-女': 'gu-IN-DhwaniNeural',
 '古吉拉特语 (印度)-Niranjan-男': 'gu-IN-NiranjanNeural',
 '印地语 (印度)-Madhur-男': 'hi-IN-MadhurNeural',
 '印地语 (印度)-Swara-女': 'hi-IN-SwaraNeural',
 '克罗地亚语 (克罗地亚)-Gabrijela-女': 'hr-HR-GabrijelaNeural',
 '克罗地亚语 (克罗地亚)-Srecko-男': 'hr-HR-SreckoNeural',
 '匈牙利语 (匈牙利)-Noemi-女': 'hu-HU-NoemiNeural',
 '匈牙利语 (匈牙利)-Tamas-男': 'hu-HU-TamasNeural',
 '冰岛语 (冰岛)-Gudrun-女': 'is-IS-GudrunNeural',
 '冰岛语 (冰岛)-Gunnar-男': 'is-IS-GunnarNeural',
 '爪哇语 (印度尼西亚)-Dimas-男': 'jv-ID-DimasNeural',
 '爪哇语 (印度尼西亚)-Siti-女': 'jv-ID-SitiNeural',
 '格鲁吉亚语 (格鲁吉亚)-Eka-女': 'ka-GE-EkaNeural',
 '格鲁吉亚语 (格鲁吉亚)-Giorgi-男': 'ka-GE-GiorgiNeural',
 '哈萨克语 (哈萨克斯坦)-Aigul-女': 'kk-KZ-AigulNeural',
 '哈萨克语 (哈萨克斯坦)-Daulet-男': 'kk-KZ-DauletNeural',
 '高棉语 (柬埔寨)-Piseth-男': 'km-KH-PisethNeural',
 '高棉语 (柬埔寨)-Sreymom-女': 'km-KH-SreymomNeural',
 '卡纳达语 (印度)-Gagan-男': 'kn-IN-GaganNeural',
 '卡纳达语 (印度)-Sapna-女': 'kn-IN-SapnaNeural',
 '老挝语 (老挝)-Chanthavong-男': 'lo-LA-ChanthavongNeural',
 '老挝语 (老挝)-Keomany-女': 'lo-LA-KeomanyNeural',
 '立陶宛语 (立陶宛)-Leonas-男': 'lt-LT-LeonasNeural',
 '立陶宛语 (立陶宛)-Ona-女': 'lt-LT-OnaNeural',
 '拉脱维亚语 (拉脱维亚)-Everita-女': 'lv-LV-EveritaNeural',
 '拉脱维亚语 (拉脱维亚)-Nils-男': 'lv-LV-NilsNeural',
 '马其顿语 (北马其顿共和国)-Aleksandar-男': 'mk-MK-AleksandarNeural',
 '马其顿语 (北马其顿共和国)-Marija-女': 'mk-MK-MarijaNeural',
 '马拉雅拉姆语 (印度)-Midhun-男': 'ml-IN-MidhunNeural',
 '马拉雅拉姆语 (印度)-Sobhana-女': 'ml-IN-SobhanaNeural',
 '蒙古语 (蒙古)-Bataa-男': 'mn-MN-BataaNeural',
 '蒙古语 (蒙古)-Yesui-女': 'mn-MN-YesuiNeural',
 '马拉地语 (印度)-Aarohi-女': 'mr-IN-AarohiNeural',
 '马拉地语 (印度)-Manohar-男': 'mr-IN-ManoharNeural',
 '马耳他语 (马耳他)-Grace-女': 'mt-MT-GraceNeural',
 '马耳他语 (马耳他)-Joseph-男': 'mt-MT-JosephNeural',
 '缅甸语 (缅甸)-Nilar-女': 'my-MM-NilarNeural',
 '缅甸语 (缅甸)-Thiha-男': 'my-MM-ThihaNeural',
 '尼泊尔语 (尼泊尔)-Hemkala-女': 'ne-NP-HemkalaNeural',
 '尼泊尔语 (尼泊尔)-Sagar-男': 'ne-NP-SagarNeural',
 '荷兰语 (比利时)-Arnaud-男': 'nl-BE-ArnaudNeural',
 '荷兰语 (比利时)-Dena-女': 'nl-BE-DenaNeural',
 '波兰语 (波兰)-Marek-男': 'pl-PL-MarekNeural',
 '波兰语 (波兰)-Zofia-女': 'pl-PL-ZofiaNeural',
 '普什图语 (阿富汗)-Gul Nawaz-男': 'ps-AF-GulNawazNeural',
 '普什图语 (阿富汗)-Latifa-女': 'ps-AF-LatifaNeural',
 '葡萄牙语 (葡萄牙)-Duarte-男': 'pt-PT-DuarteNeural',
 '葡萄牙语 (葡萄牙)-Raquel-女': 'pt-PT-RaquelNeural',
 '罗马尼亚语 (罗马尼亚)-Alina-女': 'ro-RO-AlinaNeural',
 '罗马尼亚语 (罗马尼亚)-Emil-男': 'ro-RO-EmilNeural',
 '俄语 (俄罗斯)-Svetlana-女': 'ru-RU-SvetlanaNeural',
 '俄语 (俄罗斯)-Dmitry-男': 'ru-RU-DmitryNeural',
 '僧伽罗语 (斯里兰卡)-Sameera-男': 'si-LK-SameeraNeural',
 '僧伽罗语 (斯里兰卡)-Thilini-女': 'si-LK-ThiliniNeural',
 '斯洛伐克语 (斯洛伐克)-Lukas-男': 'sk-SK-LukasNeural',
 '斯洛伐克语 (斯洛伐克)-Viktoria-女': 'sk-SK-ViktoriaNeural',
 '斯洛文尼亚语 (斯洛文尼亚)-Petra-女': 'sl-SI-PetraNeural',
 '斯洛文尼亚语 (斯洛文尼亚)-Rok-男': 'sl-SI-RokNeural',
 '索马里语 (索马里)-Muuse-男': 'so-SO-MuuseNeural',
 '索马里语 (索马里)-Ubax-女': 'so-SO-UbaxNeural',
 '阿尔巴尼亚语 (阿尔巴尼亚)-Anila-女': 'sq-AL-AnilaNeural',
 '阿尔巴尼亚语 (阿尔巴尼亚)-Ilir-男': 'sq-AL-IlirNeural',
 '塞尔维亚语 (塞尔维亚)-Nicholas-男': 'sr-RS-NicholasNeural',
 '塞尔维亚语 (塞尔维亚)-Sophie-女': 'sr-RS-SophieNeural',
 '巽他语 (印度尼西亚)-Jajang-男': 'su-ID-JajangNeural',
 '巽他语 (印度尼西亚)-Tuti-女': 'su-ID-TutiNeural',
 '斯瓦希里语 (肯尼亚)-Rafiki-男': 'sw-KE-RafikiNeural',
 '斯瓦希里语 (肯尼亚)-Zuri-女': 'sw-KE-ZuriNeural',
 '斯瓦希里语 (坦桑尼亚)-Daudi-男': 'sw-TZ-DaudiNeural',
 '斯瓦希里语 (坦桑尼亚)-Rehema-女': 'sw-TZ-RehemaNeural',
 '泰米尔语 (印度)-Pallavi-女': 'ta-IN-PallaviNeural',
 '泰米尔语 (印度)-Valluvar-男': 'ta-IN-ValluvarNeural',
 '泰米尔语 (斯里兰卡)-Kumar-男': 'ta-LK-KumarNeural',
 '泰米尔语 (斯里兰卡)-Saranya-女': 'ta-LK-SaranyaNeural',
 '泰米尔语 (马来西亚)-Kani-女': 'ta-MY-KaniNeural',
 '泰米尔语 (马来西亚)-Surya-男': 'ta-MY-SuryaNeural',
 '泰米尔语 (新加坡)-Anbu-男': 'ta-SG-AnbuNeural',
 '泰卢固语 (印度)-Mohan-男': 'te-IN-MohanNeural',
 '泰卢固语 (印度)-Shruti-女': 'te-IN-ShrutiNeural',
 '土耳其语 (土耳其)-Ahmet-男': 'tr-TR-AhmetNeural',
 '土耳其语 (土耳其)-Emel-女': 'tr-TR-EmelNeural',
 '乌克兰语 (乌克兰)-Ostap-男': 'uk-UA-OstapNeural',
 '乌克兰语 (乌克兰)-Polina-女': 'uk-UA-PolinaNeural',
 '乌尔都语 (印度)-Gul-女': 'ur-IN-GulNeural',
 '乌尔都语 (印度)-Salman-男': 'ur-IN-SalmanNeural',
 '乌尔都语 (巴基斯坦)-Asad-男': 'ur-PK-AsadNeural',
 '乌尔都语 (巴基斯坦)-Uzma-女': 'ur-PK-UzmaNeural',
 '乌兹别克语 (乌兹别克斯坦)-Madina-女': 'uz-UZ-MadinaNeural',
 '乌兹别克语 (乌兹别克斯坦)-Sardor-男': 'uz-UZ-SardorNeural',
 '祖鲁语 (南非)-Thando-女': 'zu-ZA-ThandoNeural',
 '祖鲁语 (南非)-Themba-男': 'zu-ZA-ThembaNeural'}









